### ISSUE TITLE
Addon not compatible with 70.0 or later

### ISSUE THREAD

**Issue by schneeschmelze** [protz/Manually-Sort-Folders#102]
Just a reminder that there was a [report](https://addons.thunderbird.net/de/thunderbird/addon/manually-sort-folders/reviews/1158781/) on AMO about the add-on not working in the upcoming TB 70.0b3, not sure whether this has been fixed by now:
> Does not work with Thunderbird 70.0b3 . Will not open custom folder ie Inbox. Please update. Great add-on.

**Comment by tooomm** [comment]
Even though the version number is different, I guess that's why...
Thunderbird will stop supporting MailExtension (also ones that have legacy support).

Addons need to finally be converted to real MailExtension or Web Extension: https://developer.thunderbird.net/add-ons/tb78

**Comment by Gluups** [comment]
Hello,
@rodalpho reported in different threads about version 68 that Manually Sort Folders does not work in Thunderbird 77.
If I follow properly, he should read here ?

**Comment by rodalpho** [comment]
Yes, broken in TB77 and 78 betas.

**Comment by protz** [comment]
An update for anyone checking in and seeing what's happening with this addon and future versions of Thunderbird. Basically, the addon is broken by default until I rewrite some bits of it to be compatible with future versions of Thunderbird.

*For sorting accounts:* Thunderbird developers have committed to allowing sorting accounts (*not* folders) directly within Thunderbird, without the need for an addon. This will reuse some code that I (and others) wrote, which allows *arbitrary* reordering of accounts, meaning that this will be fixed automatically when the next version of Thunderbird comes out.

See https://bugzilla.mozilla.org/show_bug.cgi?id=244347 for a timeline and discussion.

*For sorting folders:* I have outlined some plans to add the functionality to Thunderbird here: https://bugzilla.mozilla.org/show_bug.cgi?id=1606664 but this requires a fair amount of work on my side, so unlikely to happen soon.

*For picking the default startup folder:* probably much simpler than sorting folders, but nothing yet to announce.

**Comment by rodalpho** [comment]
"Description • 16 years ago". 

Classic Mozilla.

**Comment by schneeschmelze** [comment]
Anyway, if sortable accounts should arrive at Thunderbird core some day, this would be a major step forward indeed. I remember about only a few months ago Thunderbird developers declining my urgent request with regard to MSF failing. I'm looking forward to the new Thunderbird with sortable accounts at least, albeit folders will still be available in alphabetical order only.

**Comment by blacklion** [comment]
To be honest, it is simply painful to see purely technical "Junk" folder higher than all-important "Mailing Lists" hierarchy of folders. It could be nit-picking, but it is really annoying to be unable to put important folders first and unimportant and technical ones last!

Alphabetical order is nonsense to me :(

It is not complain to the extension author, I understand, that ball is on Thunderbird side.

This, and Enigmail deprecation without viable replacement (internal implementation is half-baked and crashes on import of my key collection), but still there is no direction to run, Thunderbird is last classic e-mail client on Windows :-(

**Comment by wsmwk** [comment]
On 9/22/20 8:31 AM, Lev Serebryakov wrote:
>
> This, and Enigmail deprecation without viable replacement (internal 
> implementation is half-baked and crashes on import of my key 
> collection), but still there is no direction to run, Thunderbird is 
> last classic e-mail client on Windows :-(
>
I little off topic, but did you take advantage of the testing period 
that was announced many weeks ago to enigmail users?  More participant 
testing = a better release.

I believe the crash is being worked on.

**Comment by blacklion** [comment]
> I little off topic, but did you take advantage of the testing period that was announced many weeks ago to enigmail users?  
>More participant testing = a better release. I believe the crash is being worked on.
No, because I need my GPG working. Yes, crash is worked on, and I've sent test case to developers, I hope it will be fixed soon. But I know nothing about working on GPGCard support, for example, and my main keys are on YubiKey. It is good that I had offline backup of them and I could temporary import them to keyring, but I don't want to have them here forever. It is Ok why I'm not traveling and my system is "stationary", but not when I'll need to have my mail on laptop later, when COVID situation will be resolved. I need to think what to do with this now.

**Comment by itagagaki** [comment]
I modified the Thunderbird 68 version of this add-on to work with Thunderbird 78. And I have sent a [pull-request](https://github.com/protz/Manually-Sort-Folders/pull/126).
If you're a developer, please check it out.

**Comment by blacklion** [comment]
> 
> 
> I modified the Thunderbird 68 version of this add-on to work with Thunderbird 78. And I have sent a [pull-request](https://github.com/protz/Manually-Sort-Folders/pull/126).
> If you're a developer, please check it out.

oh wow, I'll give it a try

**Comment by blacklion** [comment]
> If you're a developer, please check it out.

Seems to work for me! Thanx!

**Comment by msebald** [comment]
> I modified the Thunderbird 68 version of this add-on to work with Thunderbird 78. And I have sent a [pull-request](https://github.com/protz/Manually-Sort-Folders/pull/126).

I downloaded the files from the pull-request/fork, created a xpi file and installed it. Works for me on Thunderbird 78. Even the sort order of the folders are there again like in Thunderbird 68. :-) No idea if it works perfect, but at least it looks like it after testing it for some minutes.

Thank you very much for this fix!

**Comment by schneeschmelze** [comment]
Thank you so much for providing the bugfix! This sounds really amazing. Could you please provide the xpi file asap?

**Comment by msebald** [comment]
> Thank you so much for providing the bugfix! This sounds really amazing. Could you please provide the xpi file asap?

This is the file I used:
[Manually-Sort-Folders.xpi.zip](https://github.com/protz/Manually-Sort-Folders/files/5277549/Manually-Sort-Folders.xpi.zip)

You need to change the file extension from .xpi.zip to .xpi - as Github does not accept .xpi files.

As written above, it is just a download of the pull-request and also contains all the Git files and so on. The maintainer should release a "real" new version into public.

**Comment by BillH99999** [comment]
Works great for me as well.  Hopefully Jonathan will publish a "real" release into the public.

Thanks @itagagaki

**Comment by itagagaki** [comment]
It has yet to go through a review.
So feel free to use an xpi made from my pull request, but at your own risk.
However, the actual changes to the original code have been minimal, so I don't think an official release is too far away :-)

**Comment by rodalpho** [comment]
Yay! Thanks so much for working on this, really appreciate it.

**Comment by lgbaldoni** [comment]
Likewise.
This is one of the three must-have extensions, looking forward to an official release!

**Comment by au7oma7** [comment]
Seems to be working on 78.3.1 
+ My sorting scheme before auto update from 68.x is there too

Nice @itagagaki !

**Comment by DavidBE-UK** [comment]
Yay. Just found 2.0.2 at https://jonathan.protzenko.fr/manually-sort-folders/ . Installed, closed then re-opened TB 78.3.1, and my local folders were back to the way I had them in TB 68 and earlier.Many thanks.

I presume this is before the change to get it to add Manually sort folders to the hamburger tools menu as it's not there, but is in the menu bar tools menu.

**Comment by protz** [comment]
2.0.3 has the hamburger menu fix and is currently pending review... should be approved shortly

please continue to shower @itagagaki with praise -- well-deserved!

**Comment by DavidBE-UK** [comment]
Yes, huge thanks @itagagaki :}

**Comment by schneeschmelze** [comment]
Just to let you know that the new version has already gone live on ATN and updated on my machine. It's magic! :) Thanks a lot for the update!
