### ISSUE TITLE
[Solved] No access to sort in TB 68.2.0 / Win 7 Pro.  [Available at Tools > Add-on Options, but not in hamburger AppMenu]

### ISSUE THREAD

**Issue by LaurentGrenet** [protz/Manually-Sort-Folders#105]
Hi,

I just upgraded to Thunderbird 68.2.0 (under Win 7 Pro).... and there is no more ability to sort folders.
Extension is active, but no menu nowhere (neither under Modules menu, nor Options, nor tools, nor any other menu) to get its option page, and change current sorting.

Thanks in advance for fixing... or provide detailed explanations on how to.

**Comment by schneeschmelze** [comment]
Am 29.10.19 um 09:04 Uhr schrieb LaurentGrenet:
> I just upgraded to Thunderbird 68.2.0 (under Win 7 Pro).... and there is
> no more ability to sort folders.
> Extension is active, but no menu nowhere (neither under Modules menu,
> nor Options, nor tools, nor any other menu) to get its option page, and
> change current sorting.


Did you also upgrade to Manually sort folders 2.0.2?

**Comment by LaurentGrenet** [comment]
Yes, sure. 
Before doing it, "Manually Sort Folders" was "deactivated" due to incompatibility with new version of TB

**Comment by LaurentGrenet** [comment]
BTW, I just did a test : completely remove the module, then re-download the .xpi file and re-install it.
But unfortunately, that doesn't fix the issue :-(

**Comment by LaurentGrenet** [comment]
Ooops ! Found !
Actually, option is available in tool menu.... of Menu bar.
But not in tool menu of "three lines" button.

**Comment by LaurentGrenet** [comment]
I re-opened the issue because it may help people having the same.... and closed issues are no more visible (at least by default)
And to be clear, I edited the title to add [Solved]

**Comment by tooomm** [comment]
Had the same problem, and went mad. :D
There is already an issue for that since *some* time: https://github.com/protz/Manually-Sort-Folders/issues/22 :)

**Comment by nunoperalta** [comment]
I was all this time waiting for a "fix" to come, because I couldn't find this under "Add-on Options"...
I saw this page now, and see that it's actually present in the root of the "Tools" menu!
Thanks!!

**Comment by wsmwk** [comment]
As previously mentioned this is issue #22 - we should keep only that issue open.
