### ISSUE TITLE
v1.2.1, TB 60.9.1, no accounts shown

### ISSUE THREAD

**Issue by quicktrick** [protz/Manually-Sort-Folders#106]
It worked fine until the last stable version of TB 60.9.1.  Now it does not show the accounts again, unfortunately.  Could you please fix it?  The stable TB 60.x.x version is the last one working with many other add-ons, there is no chance to upgrade to betas yet.

Thank you very much in advance!

**Comment by schneeschmelze** [comment]
+1.

Probably the only way to fix it would be to make MSF a real Mail Extension.

**Comment by ohmer1** [comment]
Yes, have the same problem! Only local folders appears, no more imap folders.

**Comment by wsmwk** [comment]
60.9.1 had only [one small change,](https://www.thunderbird.net/en-US/thunderbird/60.9.1/releasenotes/) so it's difficult to believe that had direct impact to MSF not working.  

Note, it is working in version 68.

**Comment by protz** [comment]
I fixed a variety of things that seem to have made the issue disappear in the version that's compatible with 68, so seeing the limited time I have for this, I'm inclined to close this issue since supporting both 68 and 60 at the same time is unrealistic.

Thanks,

Jonathan
