### ISSUE TITLE
Tbird 68.3.1 update broke it

### ISSUE THREAD

**Issue by GetIT-GotIT-Good** [protz/Manually-Sort-Folders#109]
Windows 10 Pro

Folder listing populates new window, but no controls appear, thus no functionality.

**Comment by ondrasvoboda** [comment]
Also moving local folders on top using default account option is not working in this version.

**Comment by elgonzo** [comment]
Duplicate of https://github.com/protz/Manually-Sort-Folders/issues/101

**Comment by protz** [comment]
Duplicate of #112 -- can you comment there if you're still experiencing the issue?
