### ISSUE TITLE
Sent unsent messages greyed out after upgrade to TB68.3.1 and upgrade the add on

### ISSUE THREAD

**Issue by hdoothr** [protz/Manually-Sort-Folders#111]
Before TB 68.3.1 I used manually sort folders and used the function "send unsent messages" without problems. 
It appears, that when the settings in "manually sort folders" of default account is set to an other option than "1st RSS- or emailaccount in the list" the function "send unsent messages" is greyed out.

**Comment by protz** [comment]
I believe this will be fixed along with #101 which will change the account sorting method to something "proper".
