### ISSUE TITLE
Accounts list not showing

### ISSUE THREAD

**Issue by ImonitMedia** [protz/Manually-Sort-Folders#112]
![image](https://user-images.githubusercontent.com/1983016/72086517-f6af7f80-32fe-11ea-8e2c-e4078ba51f6c.png)

I am using v2.0.2 of the addon with thunderbird 68.3.1

**Comment by protz** [comment]
Are you still experiencing this issue?

**Comment by protz** [comment]
Duplicate of #57 maybe?

**Comment by ZTHawk** [comment]
I am using 2.0.5 on my laptop with TB 78.3.3 (x64). I have the same issue.

PS:
On my PC everything is working fine.

**Comment by ZTHawk** [comment]
Just found the issue:
I had an account in the settings which did not exist. According to config I have 8 accounts (1-8) and account 4 does not exist anymore.
I have changed this:
1. extensions.tbsortfolders@xulforum.org.accounts
    - Removed the bad account from the enumeration
2. extensions.tbsortfolders@xulforum.org.defaultaccount
    - Changed bad account to the one representing the local folder
3. mail.accountmanager.defaultaccount
    - Changed bad account to the one representing the local folder

**Comment by itagagaki** [comment]
@ImonitMedia @ZTHawk
Version 2.1.0 is now available on [ATN](https://addons.thunderbird.net/addon/manually-sort-folders/) .
Can you please update and try?

**Comment by itagagaki** [comment]
We have not received any reports that this issue has been resolved. But I consider this is obsolete. So I will close this.
