### ISSUE TITLE
Can't promote Local Folder to be the first account

### ISSUE THREAD

**Issue by websharkpb** [protz/Manually-Sort-Folders#114]
Howdy

I was able to make the 'Local Folders' be the first account under Sort Accounts, but no matter what I do in sort folders under 68.4.1, it continually sits at the bottom.

Is this broken?

Cheers
Paul

**Comment by iprotony** [comment]
I'm having the same issue on all our PCs in the office. It was useful until Thunderbird automatically updated and defaulted my local Unified email folder to last.

Thank you!

**Comment by Webdongle** [comment]
Confirmed.  This happened before and got sorted.  Appears to happen after Thunderbird updates

**Comment by Webdongle** [comment]
Looks like it has been fixed Version 2.0.2 4th Feb

**Comment by elgonzo** [comment]
Duplicate of issue https://github.com/protz/Manually-Sort-Folders/issues/101

**Comment by protz** [comment]
Update: Thunderbird developers have committed to allowing sorting accounts (*not* folders) directly within Thunderbird, without the need for an addon. This will reuse some code that I (and others) wrote, which allows *arbitrary* reordering of accounts, meaning that this bug will be fixed automatically when the next version of Thunderbird comes out.

See https://bugzilla.mozilla.org/show_bug.cgi?id=244347 for a timeline and discussion.
