### ISSUE TITLE
Sorting window is not resizable making it difficult to work with

### ISSUE THREAD

**Issue by bonbonbillo** [protz/Manually-Sort-Folders#116]
I have many email accounts, then when I try to sort manually and found the list is out of the screen including the plugin´s buttons. It´s better add a scroll bar.

**Comment by LeKoe** [comment]
Same problem here,
Windows 10, Thunderbird 68.4.2 (64 bit)
Add-on is unusable as the buttons are out of the window.

**Comment by aberja** [comment]
I too have this issue where the plugin's top has disappeared above the top of my monitor and the bottom has disappeared below the bottom of my monitor.  As a result, I can only see a partial list of my accounts and the buttons are missing.  Unfortunately, this renders the plugin unusable.  
Windows 10, Thunderbird 68.5.0 (64 bit), Manually Sort Folders version 2.0.2

**Comment by GitHubbet** [comment]
Me too!
Surprised to suddenly be off screen.

I even set resolution lower, then run it and reset resolution higher so I would reach top of window.

Even with that, I cannot reach bottom of window to APPLY !

HELP please - thanks [I am on version TB 68.8.0 - MSF 2.02

Thanks

**Comment by bellingeri** [comment]
Hi.
I have fixed the tbsortfolders.xul file with a little change: Adding the style "max-height: 800px;" to the <window> tag, the window is limited in height allowing its use.

I made a "pull request" for this.

**Comment by protz** [comment]
I'm going to leave this on hold as the folder sorting functionality will have to undergo a complete rewrite anyhow for future versions of Thunderbird. I'll fix this while I'm at it.

**Comment by despecial** [comment]
@protz possible to share the current state for the folder sorting problem? I updated to TB 68 lately and miss the "Local Folders" above my accounts. Hopefully you can fix this.

Is there a bug report or feature request thread on Mozilla?

**Comment by msprotz** [comment]
This is an inner limitation of Thunderbird that I cannot workaround with the addon. See https://bugzilla.mozilla.org/show_bug.cgi?id=244347 for progress on fixing this bug within Thunderbird.

**Comment by protz** [comment]
The original issue was fixed via https://github.com/protz/Manually-Sort-Folders/pull/130 -- I just pushed 2.0.5 on addons.thunderbird.net which should be available shortly.
