### ISSUE TITLE
When setting the default folder, move the focus on the first message of the list

### ISSUE THREAD

**Issue by alexarnaud** [protz/Manually-Sort-Folders#118]
Hello all,

Many thanks all for the creation of this extension. 

I'm visual-impaired and I help blind users to use their computer, we'd like to use your extension to set a default folder.

To make the set default folder practical for keyboard-only users like blind could you please make the focus on the highest message of the list?

Best regards.

**Comment by alexarnaud** [comment]
It seems there is an implementation on the feature on another extension here: https://github.com/vanowm/TB-Auto-Select-Latest-Message/blob/master/src/bootstrap.js

The problem whith the Auto Select Last Message is mainly that it doesn't do it only at startup it do it when you move between folder with the keyboard.

**Comment by itagagaki** [comment]
It has been a long time since you requested it.
Do you still need the feature?
I think you should have made this request to the author of Auto Select Last Message. Why didn't you?

**Comment by cwendling** [comment]
We're trying to work with upstream on a fix at https://bugzilla.mozilla.org/show_bug.cgi?id=1620310, and anyway this addon doesn't seem to be the right place for such a setting.

Thanks for your concerns though :)

**Comment by alexarnaud** [comment]
Thanks a lot @cwendling, closing this issue.
