### ISSUE TITLE
Seamonkey compatibility

### ISSUE THREAD

**Issue by commander-keen** [protz/Manually-Sort-Folders#12]
Would be nice to see this working in Seamonkey 2.0.x or at least 2.1.x, too besides Thunderbird.
http://www.seamonkey-project.org/
https://addons.mozilla.org/en-US/seamonkey/?browse=featured

Right now the Folder-List is empty and the following errors are reported in the eerror-console:

Error: uncaught exception: [Exception... "Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [nsIXPCComponents_Utils.import]"  nsresult: "0x80520012 (NS_ERROR_FILE_NOT_FOUND)"  location: "JS frame :: chrome://tbsortfolders/content/ui.js :: <TOP_LEVEL> :: line 5"  data: no]

Error: tbsf_prefs is undefined
Source File: chrome://tbsortfolders/content/ui.js
Line: 149

**Comment by itagagaki** [comment]
MSF for SeaMonkey is now available.
https://addons.thunderbird.net/ja/seamonkey/addon/manually-sort-folders-sm/

Try it out.

**Comment by itagagaki** [comment]
Development complete
