### ISSUE TITLE
Unable to have RSS Feeds moved to top

### ISSUE THREAD

**Issue by jeremymeyers** [protz/Manually-Sort-Folders#120]
On Tbird 68.8 and plugin 2.0.2.  Have "RSS Feeds" moved to top in the plugin options dialog, but it only displays all the way on the bottom, regardless of where i move it.

**Comment by Gluups** [comment]
Hello Jeremy,
Perhaps one of the developers will give you a more precise answer, but this point has been broached sometimes in different feedbacks, so I can repeat you what was answered.
Thunderbird has evolved in the way of less flexibility on this topic, and it is no more possible to get the newsgroups or RSS feeds before the mail accounts -this was not a choice at the extension level.
So, if this point if of importance to you you can imagine to use an older version of Thunderbird, but please keep in mind that newer versions solve security problems, so by using an older version you assume a risk. To better evaluate it you have to study the versions notes.

**Comment by protz** [comment]
Update: Thunderbird developers have committed to allowing sorting accounts (*not* folders) directly within Thunderbird, without the need for an addon. This will reuse some code that I (and others) wrote, which allows *arbitrary* reordering of accounts, meaning that this bug will be fixed automatically when the next version of Thunderbird comes out.

See https://bugzilla.mozilla.org/show_bug.cgi?id=244347 for a timeline and discussion.
