### ISSUE TITLE
degrade on 2.0.4

### ISSUE THREAD

**Issue by itagagaki** [protz/Manually-Sort-Folders#128]
@protz I found that you degraded ui.js (turned into an ancestor) at the commit:
https://github.com/protz/Manually-Sort-Folders/commit/3ed7b3a2bb8cd261e80ea92625d40d07d8cf65e5

**Comment by itagagaki** [comment]
I sent new pull request. That resolve both https://github.com/protz/Manually-Sort-Folders/issues/116 and this issues.

**Comment by protz** [comment]
Switching to createXULElement instead of createElementNS was a request from @jobisoft -- are you saying that `createXULElement` is only working in Tb 78 and later? Pinging John for some authoritative answer... thanks! :)

**Comment by itagagaki** [comment]
Oh, this was not a degrade! I thought you used the old code createElement, but it was createXULElement.
Forgive me for my mistake.
That depends on John's answer. I'll leave that to you.
I'll make a fix branch for https://github.com/protz/Manually-Sort-Folders/issues/116 only.

**Comment by jobisoft** [comment]
`createXULElement` works in TB68 ESR. I suggest to keep using that instead of `createElementNS` for XUL elements.

**Comment by protz** [comment]
Many thanks for your prompt response John! Much appreciated.

@itagagaki no worries at all -- I understand that the change might have looked suspicious, and I should've provided a more meaningful commit message
