### ISSUE TITLE
Sort multiple local folders (Support for add-on 'LocalFolders')

### ISSUE THREAD

**Issue by Nick222** [protz/Manually-Sort-Folders#13]
When I use addon LocalFolder https://addons.mozilla.org/ru/thunderbird/addon/localfolder/ and create another local folder - I cannot sort it with Manually sort folders addon - to put second local folder before first one (for example).

**Comment by itagagaki** [comment]
It was not possible to move the order of local folders with MSF, which was compatible with previous versions of Thunderbird.

The combination of Thunderbird 91 and MSF 2.1.0 may have the ability to do it, but unfortunately the LocalFolers add-on (currently 3.0.1) does not seem to be compatible with Thunderbird 91.

**Comment by itagagaki** [comment]
The add-on LocalFolders is now version 3.2 and being Thunderbird 91 compatible.
Thunderbird 91 is able to move the order of local folders, so this problem is solved.
You can also use MSF 2.1.0's account sorting feature to move the order of local folders.
