### ISSUE TITLE
Thunderbird opens on start page

### ISSUE THREAD

**Issue by richcres** [protz/Manually-Sort-Folders#131]
Ever since the Thunderbird update (68.12.0) my last selected folder is not remembered. Now every time I start TB it goes to the start page instead of my Inbox. If I disable "Manually Sort Folders" this issue does not occur. Prior to the 68.12.0 update TB would remember the last selected folder with "MSF" enabled.

**Comment by itagagaki** [comment]
Thats odd.. A little additional information please.
Open Menu Bar [Help] > [Troubleshooting Information]
and click [about:profiles]
![image](https://user-images.githubusercontent.com/71218184/94630452-c4b4d200-0300-11eb-95f7-d4e552da7224.png)
Click [Open Folder]
![image](https://user-images.githubusercontent.com/71218184/94630557-1eb59780-0301-11eb-9d0d-f98a68787388.png)
Find "prefs.js", right click and Edit. Maybe Notpad will open.
![image](https://user-images.githubusercontent.com/71218184/94630979-33465f80-0302-11eb-922e-f9250d0e0aaa.png)
Find and tell me the line that contains "startup_folder".

**Comment by richcres** [comment]
> That's odd.. A little additional information please.

> Find and tell me the line that contains "startup_folder".

user_pref("extensions.tbsortfolders@xulforum.org.startup_folder", "mailbox://xxxx%40xxxxxxx.xxx@xxxx.xxxxxxx.xxx");

The line contained my email address so I changed only that to all of the xxxxxs.

**Comment by itagagaki** [comment]
Ok, but when TB starts up, it's not a folder for that account, is it?

**Comment by protz** [comment]
looks like a folderURI for a local folder...?

**Comment by richcres** [comment]
> Ok, and when Thunderbird starts up, you're saying the folder isn't set to that xxxx@[xxxxxxx.xxx@xxxx.xxxxxxx.xxx](mailto:xxxxxxx.xxx@xxxx.xxxxxxx.xxx), is it?

When TB starts up my Comcast account (above the inbox, see attached image) is highlighted/selected. Up until recently the last folder I used was highlighted when I started TB.

![Start Page](https://user-images.githubusercontent.com/72110286/94696606-38f17480-0305-11eb-8258-8f12385c359a.jpg)

**Comment by itagagaki** [comment]
Oh, I get it.
Then it's strange that prefs.js has the line contains "startup_folder".
I guess you selected "Use a custom folder" in MSF's Extra settings.
Switch it to "Use last opened folder".
![image](https://user-images.githubusercontent.com/71218184/94702506-ce7a1c00-0378-11eb-8cbb-e7bc907a058b.png)

**Comment by richcres** [comment]
> Oh, I get it.
> Then it's strange that prefs.js has the line contains "startup_folder".
> I guess you selected "Use a custom folder" in MSF's Extra settings.
> Switch it to "Use last opened folder".

No I never selected or changed any setting for MSF. In fact I don't have a setting window for MSF, when I bring up tools/add-on options it tells me "No add-ons settings found."

**Comment by itagagaki** [comment]
Can you confirm the following steps?

Open Menu Bar [Tools] > [Manually sort folders]
![image](https://user-images.githubusercontent.com/71218184/94705722-557cc380-037c-11eb-89e6-bc71f16688e5.png)

Click "Extra settings" tab
![image](https://user-images.githubusercontent.com/71218184/94706319-01beaa00-037d-11eb-93d9-67fe291e57b3.png)

**Comment by richcres** [comment]
> Can you confirm the following steps?
> 
> Open Menu Bar [Tools] > [Manually sort folders]
> Click "Extra settings" tab

WOW, never saw that until you pointed it out. Found the setting and changed it, everything is back to working as it should, thank you.
