### ISSUE TITLE
Add sorting identities

### ISSUE THREAD

**Issue by BK-20** [protz/Manually-Sort-Folders#137]
I want Manually-Sort-Folders to be expanded to sort identities (like "user_pref("mail.identity.id..." in prefs.js) as well. I work a lot with identities in order to fight SPAM, and it works well. But since I got several hundreds of these "aliases", choosing the right identity gets more and more painful because they don't follow any order. So sorting them alphabetically would help a lot, finding by entering a string or parts of it could even help more. This applies to folder settings (From Account) as well as choosing the identity while writing a message.

**Comment by BK-20** [comment]
Also welcome: create new identities by it's own. TB needs several minutes to create a new identity, so meanwhile I close Thunderbird and manipulate prefs.js using a shell script, then start TB again to continue...

**Comment by itagagaki** [comment]
Do you mean you want to sort the order of using ids for each account?

**Comment by BK-20** [comment]
Not necessarily, for me, it is good enough how it works meanhwile.

**Comment by BK-20** [comment]
1.: I create e new identity. 
2.: I assign this new identity to the folder as the _From Account_ in the _Folder Account_ tab of the folder settings. Therefore I choose this identity from the select list. If this list is very long, this is laborious, if this list is not sorted alphabetically.

This was the case when I opened the case, but meanwhile the list is sorted. So my wish is satisfied. From my view, the case can be closed.

**Comment by itagagaki** [comment]
Thanks for the detailed explanation. Since you don't seem to need it anymore, and there doesn't seem to be much demand for it from others, I will close this issue.

**Comment by Francewhoa** [comment]
For those facing the same challenge, this "**Correct Identity**" add-on might be useful at https://addons.thunderbird.net/fr/thunderbird/addon/correct-identity/


> Correct Identity helps you to use the right identity when sending messages by:
> 
>    * letting you better configure default identities to be used when composing new messages from scratch.
>    * detecting and using the identity for which you received the message you're replying.
>    * you can improve this detection by specifying aliases (alternate addresses, sender names, domains, etc., regular expressions supported), or instead opt-out identities for detection.
>    * changing identities on the fly when typing recipients that match aliases.
>    * warn you before sending a message from an identity if its recipients match one or more search terms you configured for the identity (regular expressions supported).
