### ISSUE TITLE
Won't work in 68.12.1

### ISSUE THREAD

**Issue by ZbynekT** [protz/Manually-Sort-Folders#144]
I've installed your great add-on for thunderbird  "Manually sort folders" to my Thunderbird in version 45.x.x where it worked fine. I used it for accounts re-ordering.
Now, I've updated Thunderbird to version 68.12.1 and it stopped working.
I can see UI of the add-on and re-arrange items/accounts, but application doesn't work. The result is unchanged.
I'm adding output from Error log console. It was cleared before starting the add-on and recorded.
My version of the add-on is 2.0.6

**Comment by schneeschmelze** [comment]
Version 2.0.6 is fit for the current version of TB. Could you give TB 78.8 a try?

**Comment by itagagaki** [comment]
@ZbynekT Where is that error log console output?

**Comment by ZbynekT** [comment]
I'm sorry... Sending log now..
[Manually_sort_folders_log_console.txt](https://github.com/protz/Manually-Sort-Folders/files/6099819/Manually_sort_folders_log_console.txt)

**Comment by ZbynekT** [comment]
In 78.8.0 the moving of the accounts works except, it doesn't work for "aggregated" account folder. In my case it is "Travis Email Storage" which I would like to have as the first account on the top of the list.
Still, I need to stay on 68.12.1 because of other add-ons which are not compatible with 78.x
![manually move folders](https://user-images.githubusercontent.com/28976519/110295932-ffc6da00-7ff1-11eb-9247-b37f5a4b0e1f.jpg)

**Comment by itagagaki** [comment]
@ZbynekT 
I've looked at the console logs and don't see anything strange.
I installed and tested TB 68.12.1 and it is working fine.
I assume you have add-ons in addition to Manually sort folders, but does disabling all of them change the situation?

**Comment by KXKVI** [comment]
I also run TB 68.12.1 with MSF version 2.06.  On the MSF UI the Sort Accounts panel is blank if I have 4 mail accounts set up.  However, if I add a 5th account, the UI shows the accounts and I can order them any way I like.  This is repeatable across 4 PC's, all running Win 10 x64.  Very strange.  Hope this helps you to track down the issue.

**Comment by BillH99999** [comment]
@ZbynekT 

I'm not sure, but it looks like you renamed Local Folders to Travis Email Storage.  If so, it is not actually an email account.  I don't believe the extension will allow you to move Local Folders before email account.

Bill

**Comment by itagagaki** [comment]
@ZbynekT How about after that?
As @ZbynekT pointed out, you cannot move a local folder in front of an Email account in the previous Thunderbird. (This is possible in the latest Thunderbird version 91).
Also, this add-on is now 2.1.0, so please try it if you like.

Can I close this issue?

**Comment by itagagaki** [comment]
We have not received any reports that this issue has been resolved. But I consider this is obsolete. So I will close this.
