### ISSUE TITLE
[Feature request] Edit folder flags

### ISSUE THREAD

**Issue by bege10** [protz/Manually-Sort-Folders#146]
Hello,
thank you very much for maintaining this extension also for latest Thunderbird versions.
Unfortunately the extension to edit folder flags https://addons.thunderbird.net/thunderbird/addon/folderflags is no longer maintained. I think that this feature would well fit into your extension. Could you, please, add this feature to Manually-Sort-Folders?

**Comment by itagagaki** [comment]
I see. Ryan Lee doesn't seem to be interested in addressing the issue at the moment.
I'll consider it.

**Comment by itagagaki** [comment]
FolderFlags has been successfully updated for TB78.
So this feature request is rejected and closed.

**Comment by bege10** [comment]
I've never been so happy and grateful for a rejected request 😉
