### ISSUE TITLE
How do I use it?

### ISSUE THREAD

**Issue by bwilson** [protz/Manually-Sort-Folders#148]
Hi,
I installed this plugin, but I have not noticed any difference in Thunderbird, and I don't see any instructions. How do I sort my folders?

Thanks!
-Ben

**Comment by schneeschmelze** [comment]
Am 13.04.21 um 20:38 Uhr schrieb bwilson:
> I installed this plugin, but I have not noticed any difference in
> Thunderbird, and I don't see any instructions. How do I sort my folders?

Please take a look into your Extras menu. There you should find an entry
for sorting your accounts and your folders.

**Comment by bwilson** [comment]
I don't see an Extras menu anywhere.

**Comment by schneeschmelze** [comment]
> I don't see an Extras menu anywhere.


It should be part of the Hamburger menu.

**Comment by bwilson** [comment]
My hamburger menu has 19 items, but none of them is Extras. I am using Thunderbird 78.7.1. Is that what you have?

**Comment by schneeschmelze** [comment]
78.9.1 on macOS. Maybe it's called differently in localisations other than German. Pls see the screenshot.
![Ohne Titel](https://user-images.githubusercontent.com/20168163/114611665-90ec3900-9ca1-11eb-823b-f2531ad8db38.png)

**Comment by bwilson** [comment]
OK, got it! That folder is called Tools on mine. I found the menu - not sure how I missed it before.

Thanks for your help!
