### ISSUE TITLE
Accounts list empty - DEBUG Exeption for JS frame - ui.js

### ISSUE THREAD

**Issue by theVitus** [protz/Manually-Sort-Folders#149]
Hi there,

[context below err msg]

any chance someone has seen this before and/or know how to deal with it?
================================
tbsortfolders.ui	DEBUG	[Exception... "Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [nsIPrefBranch.getStringPref]"  nsresult: "0x8000ffff (NS_ERROR_UNEXPECTED)"  location: "JS frame :: chrome://tbsortfolders/content/ui.js :: accounts_on_load/servers< :: line 442"  data: no] Stack trace: accounts_on_load/servers<()@ui.js:442
accounts_on_load()@ui.js:442
on_load()@ui.js:301
onload()@tbsortfolders.xhtml:1
================================

and right after that error, this one shows up:
================================
11:57:32.503 Uncaught 
Exception { name: "NS_ERROR_UNEXPECTED", message: "Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [nsIPrefBranch.getStringPref]", result: 2147549183, filename: "chrome://tbsortfolders/content/ui.js", lineNumber: 442, columnNumber: 0, data: null, stack: "accounts_on_load/servers<@chrome://tbsortfolders/content/ui.js:442:56\naccounts_on_load@chrome://tbsortfolders/content/ui.js:442:26\non_load@chrome://tbsortfolders/content/ui.js:301:5\nonload@chrome://tbsortfolders/content/tbsortfolders.xhtml:1:1\n", location: XPCWrappedNative_NoHelper }
ui.js:442
================================

**CONTEXT:**
Windows 10
Thunderbird 78.10.0 - 32-bit
Manually sort Folders 2.06

Was working like a charm for years, until this morning

**Have Tried:**
downgrade TB to 78.9.1
downgrade MSF to the first version that suports TB v78
start with only MSF enabled - all other add-ons disabled

[20210423,12.16 - console-export-2021-4-23_12-16-12.txt](https://github.com/protz/Manually-Sort-Folders/files/6366325/20210423.12.16.-.console-export-2021-4-23_12-16-12.txt)

Thanks in advance for kind attention...

Cheers
Vitus

**Comment by Gluups** [comment]
Hello,
I do not program for this extension, but perhaps a first sight can allow to gain some time.
When you see an error number, the first step is to search for it on Internet. A search of 8000FFFF shows up that this error number is most often met on Windows Update.
So, I should suggest to verify the update status of your Windows, and in case it is needed to improve that.
Not very sure it helps, but it should not worsen the situation.
Then you can give the version number of Windows, by typing VER in a command line window.
Also please verify the version number of Thunderbird, just in case (Help, About).
That way, when a programmer of the extension comes, you have already one track that is treated, and if it does not help another track can be searched for.

**Comment by itagagaki** [comment]
Hi,
Thanks for the detailed report.
I'm aware of the exception that occurs on line 442 of ui.js, and I'll try to fix it in the next release of this add-on.
However, it's only a workaround to prevent the add-on from stopping working. I believe that the real cause is something wrong with the email account data. It may be tedious, but I would appreciate it if you could try re-registering all your email accounts and try again.

**Comment by theVitus** [comment]
@itagagaki 
Thank you for the fast reply.

I kind'a suspected you'd like me to do that... so, tomorrow is Saturday and I'll have the morning free to tinker with this.
Stay tuned ;-)

PS! If there's anything else/similar that could take time to do, let me know in the next 16hs so I can do it in sequence tomorrow while I have the time to do it.

@Gluups - also thank you to you for your time and interest. The code when searched for in it's entire lenght is related to TB and not so much Windows and the TB version is in the org. msg. 


Cheers
Vitus

**Comment by theVitus** [comment]
@itagagaki...  

I took the looooooooooooooong way and did a complete uninstall (removed add-ons first), deleted profile! and then a reinstall of TB with new profile and then installed the add-ons (only 8 of them) that I use, starting with MSF.

The add-on is working now EXCEPT for one account that used to be included in the list, no longer showing up.
Okay, it is a "special" account in that it is an exchange account that comes via that add-on called Owl (https://www.beonex.com/owl/), BUT... it WAS in the list of "sort accounts" before but now it only shows up in "sort folders".

It is a pitty, because one of the main reasons for using MSF was that I wanted that particular account at the top of the list. It is now at the end, and I can't move it.

OBS! It is "funny" because when I check the "extensions.tbsortfolders@xulforum.org.tbsf_data" it has! that account listed as well.

Any suggestion for a "work around" to get it to show in the sort accounts view so I can move it up, please?!

cheers
Vitus

**Comment by theVitus** [comment]
@itagagaki - found the workaround!  I set the "missing" account as "default account" and it is now at the top of the list. That's it!
Works... all is well ;-)
cheers
Vitus

**Comment by itagagaki** [comment]
Hi @theVitus ,
First of all, I would like to say thank you for all your hard work.
And I am relieved to hear that the problem seems to have been solved as a result.
However, the information you have provided suggests that there may still be imperfections in MSF. I close this issue but I will use this information to update MSF in the future.
Thank you very much!
