### ISSUE TITLE
No folder lists after renaming an IMAP folder

### ISSUE THREAD

**Issue by clack69** [protz/Manually-Sort-Folders#15]
Hello,

I renamed a folder within an IMAP account. After that, Thunderbird's own sorting method was used for all folders (instead of the user-defined order which I selected with MSF). I tried to re-arrange the old order with MSF; the first thing I recognized was that the account appears twice now in the account select box. Selecting one of these two (identical) accounts, the folder list only shows "trash" and "inbox", but no subfolders at all.

I also tried deactiving/activating MSF, even uninstalled and reinstalled it, but there is no change: the IMAP account appears twice, and MSF shows no folders except trash and inbox.

Any idea...? Versions: TB 7.0.1, MSF 1.0.1

Kind regards,

Thom@s

**Comment by itagagaki** [comment]
@clack69 
Version 2.1.0 is now available on [ATN](https://addons.thunderbird.net/addon/manually-sort-folders/) .
Can you please update and try?

**Comment by itagagaki** [comment]
We have not received any reports that this issue has been resolved. But I consider this is obsolete. So I will close this.
