### ISSUE TITLE
Correcting example on TB add-on page

### ISSUE THREAD

**Issue by libcub** [protz/Manually-Sort-Folders#151]
The [web page](https://addons.thunderbird.net/en-US/thunderbird/addon/manually-sort-folders/?src=search) for this extension at the Thunderbird add-ons site states: "For instance, you can put a Unicode star ✸ at the beginning of your folder name to put it on top of the list without having to sort everything manually." However, as the poster of closed issue #34 points out, that Unicode character will sort _after_ basic alphanumeric characters. Also, that character is not a control code, as the wiki page here states; control codes do not have visual representations. In actuality then, there are no real displayable Unicode characters that sort before ASCII characters. Part of me thinks that is too bad, because we can't use special characters to sort before ASCII, although another part of me understands the value in having ASCII characters first. At least there are 15 ASCII symbols that sort before letters and numbers.

**Comment by itagagaki** [comment]
@libcub Thanks for the useful advice.
@protz Can you please correct the description of ATN?

**Comment by protz** [comment]
I've updated the description. Does it make any sense to keep ascending alphabetical order as an option, then?

**Comment by itagagaki** [comment]
I think it's useful :-)
I'll close this one now that the suggested update has done.
If you have another suggestion, please write a new one.
Thanks!
