### ISSUE TITLE
Exchange accounts will not sort correctly now (ExQuilla account)

### ISSUE THREAD

**Issue by RJSuryan** [protz/Manually-Sort-Folders#152]
I have multiple IMAP accounts and 2 Exchange accounts using ExQuilla in TB. Prior to today I was able to have both Exchange accounts in the #1 (default account) and the other in the #2 positions, then all of my IMAP accounts followed. Now my second Exchange account gets shoved to the bottom of all the accounts no matter what I do.

![Picture0171](https://user-images.githubusercontent.com/84160051/118205039-60b8c700-b414-11eb-9d95-34283ffec04c.jpg)

**Comment by itagagaki** [comment]
Can you please tell us your OS and the respective versions of Thunderbird and Manually Sort Folders?

**Comment by itagagaki** [comment]
This may be the same issue as #170.

**Comment by RJSuryan** [comment]
OS is Windows 10 Pro 21H1 , Thunderbird 91.6.1 64bit , MSF 2.1.2 , ExQuilla 91.2 active subription

**Comment by itagagaki** [comment]
@RJSuryan Please try our experiment in #170.
