### ISSUE TITLE
I cant reach the save button at the bottom of the plugin window.

### ISSUE THREAD

**Issue by mikikuke** [protz/Manually-Sort-Folders#154]
this is so ridiculous....how do you expect to save it if the window is outside the screen and you cant make is smaller?

I cant see restart thunderbird and close buttons because they are covered by task bar and you cant make the window smaller....
who developed this plugin....so stupid to forget something like this.....

**Comment by itagagaki** [comment]
What version are you using?
That issue was fixed last September, and at least the latest version 2.0.6 should reflect that fix.

**Comment by itagagaki** [comment]
We have not received any reports that this issue has been resolved. But I consider this is obsolete. So I will close this.
