### ISSUE TITLE
Hide icons

### ISSUE THREAD

**Issue by lars18th** [protz/Manually-Sort-Folders#157]
Hi,

This is a great plugin. Thank you!
And perhaps this request is out-of-scope for this plugin, but I expose here: Please can you add the option to hide the folder icons?

Regards.

**Comment by itagagaki** [comment]
Why do you want to hide folder icons?

**Comment by lars18th** [comment]
> Why do you want to hide folder icons?

Because they occupy space and are innecessary. In older versions I can do that. However, with recent versions of Thunderbird is impossible. And other mail clients doesn't have folder icons. Can you add an option for this, please?

**Comment by itagagaki** [comment]
Implemented on version 2.3.0
See Extra tab.

**Comment by lars18th** [comment]
> Implemented on version 2.3.0 See Extra tab.

Thank you very much @itagagaki !! 👍
