### ISSUE TITLE
How does it work?!

### ISSUE THREAD

**Issue by ivan-paleo** [protz/Manually-Sort-Folders#158]
I cannot find a way to reorder accounts or folders: drag/drop doesn't work, there is no "settings" menu, nothing with right-click, and nothing in account settings either. 
Am I missing something obvious or it just doesn't work at all?

Thunderbird 78.11.0 on macOS 11.4.

**Comment by Knimrod** [comment]
Same issue here on PC running Win 10 and Thunderbird 78.11.0.  There is no "hamburger menu" and the Tools menu does not show anything from this addon.

**Comment by ivan-paleo** [comment]
I've re-installed it, same problem...

**Comment by Knimrod** [comment]
Do you have/use McAfee AV?    Check your quarantined files.

**Comment by ivan-paleo** [comment]
No AV installed!

**Comment by jameshibbard** [comment]
Make sure that the menu bar is visible in Thunderbird (the one with entries _File_, _Edit_, _View_, _Go_ etc... You should be able to toggle it with <kbd>Alt</kbd>) , then go to _Tools_ > _Manually sort folders_

**Comment by ivan-paleo** [comment]
It was indeed under _Tools > Manually sort folders_, thanks!
Not the place I expected to find it though... Maybe something to improve, or at least document.
