### ISSUE TITLE
Blank account and folder lists? (TB91)

### ISSUE THREAD

**Issue by davidkidd** [protz/Manually-Sort-Folders#159]
Hello. I just installed this for Thunderbird 91 on Windows 10. I have no other add-ons installed.

When clicking 'Manually sort folders' in the Tools menu, I get a window without any accounts or folders to select. See attached screenshot.

Here's the folders tab. The Accounts tab is also blank.

![blank_sort](https://user-images.githubusercontent.com/199402/129311521-3f643d59-9cc0-4ead-82a9-aba621fff786.png)

**Comment by BillH99999** [comment]
Just to show that this isn't a problem for just davidkidd, I am also experiencing this same problem.  Will the add-on be updated to work with TB 91.0?  Even though TB 91.0 does allow sorting of accounts natively, it doesn't support sorting folders as far as I can see.

Thanks,
Bill

**Comment by fightuntilwedie** [comment]
Same issue here. There's simply nothing to sort!

**Comment by linuxfighter** [comment]
Same in my mac. I guess we have to wait for an update

**Comment by schneeschmelze** [comment]
A question: What do we still need MSF in TB91 for? Accounts can be sorted out of the box. If I can live with the A--Z order wrt folders, MSF might be of little use?

**Comment by fightuntilwedie** [comment]
Holy hell, you are right. At least accounts can be sorted with drag and drop. Didn't know it, yet. Thank you! But folders can't be sorted at the moment, right?

**Comment by schneeschmelze** [comment]
Sorry, I cannot tell. We probably would need a fresh profile for that. According to the release notes only accounts can be sorted.

**Comment by BillH99999** [comment]
> A question: What do we still need MSF in TB91 for? Accounts can be sorted out of the box. If I can live with the A--Z order wrt folders, MSF might be of little use?

Because I use it to sort folders which can't be done within native TB 91.0 as far as I can tell.

Bill

**Comment by 47Dgo** [comment]
I habe TB 91 installed but I do not see how I can re-order accounts.  Any help would be appreciated!

**Comment by fightuntilwedie** [comment]
Go to account settings and drag and drop the accounts in the list on the left side.

**Comment by linuxfighter** [comment]
To reorder my folder i use numbers... for example 
[1] folder
[2] folder
[3] folder
ETC

**Comment by sKippah** [comment]
> A question: What do we still need MSF in TB91 for? Accounts can be sorted out of the box. If I can live with the A--Z order wrt folders, MSF might be of little use?

Dont get what a message like this has to do in a Bug Report. If u don't like to use the App just don't use it.
Some of us like to have sorting of folders too, not only accounts.

**Comment by itagagaki** [comment]
I did a little investigation.
I figured out why the list of accounts was empty in TB91 and found a way to fix it.
However, TB91 allows you to rearrange your accounts as you wish in the account settings page. So I think MSF's role is over as far as accounts are concerned.
However, MSF has other features as well. For example, it was possible to reorder subfolders. This has not been done in TB91 itself. That feature also stopped working in TB91, but I am investigating whether we can make it work again.

**Comment by itagagaki** [comment]
I now have an idea of how to deal with TB91 for both accounts and folders.
However, I found a bug in TB91 and am reporting it in Bugzilla.
I 'm not sure if it has anything to do with MSF, but I'm waiting for a resolution on that now.

@protz Do you remember what the reason was for MSF's separate handling of email and RSS accounts, news accounts, and the rest (local folders fall into this category)? Maybe there was a special reason for TB before, but when I tried it with TB91, I had no problem treating news accounts and local accounts the same as mail accounts (i.e. I could sort them freely). If you can remember why, please let me know.

**Comment by BillH99999** [comment]
Thanks for working on this and for the updates on the status.

Bill

**Comment by pastordl** [comment]
Thank you for your hard work. Hopefully you can find the solution quickly.

**Comment by msprotz** [comment]
The only reason they were treated separately in the UI is because the underlying Thunderbird code could not cope with anything else.

Was the core Thunderbird bug fixed? Bug 244347 If so, then you should be able to treat all accounts as part of the same list that can be reordered arbitrarily.

Hope this helps!

Jonathan

**Comment by itagagaki** [comment]
@protz Thanks for the info!
I will try to find out if that bug has been fixed in TB91 and try to make a smart implementation.

**Comment by TJR032354** [comment]
I truly hope this add-on gets updated to work with TB91.... the order of my folders are already a mess !

**Comment by itagagaki** [comment]
I have finished writing the update code for TB91 and have now submitted a pull request to this repository. And I've contacted @protz  via email and am waiting for a response.
If you know how to do it, you can install and try MSF for TB91 from my repository below. Please note that it is not the official version.
https://github.com/itagagaki/Manually-Sort-Folders

**Comment by mms1406** [comment]
Hello, is there already an update to version 2.1.0 for download?

Thanks a lot
Michael

**Comment by TJR032354** [comment]
> Hello, is there already an update to version 2.1.0 for download?
> 
> Thanks a lot
> Michael

I believe the new code (zip file) has to be downloaded from the link itagagaki provided and manually installed in TB. I have been unsuccessful so far..... keep getting a file corrupt error when I try to install it

**Comment by mms1406** [comment]
> > Hello, is there already an update to version 2.1.0 for download?
> > Thanks a lot
> > Michael
> 
> I believe the new code (zip file) has to be downloaded from the link itagagaki provided and manually installed in TB. I have been unsuccessful so far..... keep getting a file corrupt error when I try to install it

I can´t se a zip file :-(

**Comment by TJR032354** [comment]
> I can´t se a zip file :-(

click on green Code drop-down button

**Comment by BillH99999** [comment]
I also tried to install the downloaded file and got the error saying it was corrupt.

Bill

**Comment by itagagaki** [comment]
Try the following steps.

1. Remove the currently installed MSF and exit TB
2. Download the zip file attached here
3. Rename it to tbsortfolders@xulforum.org.xpi
4. Move it to the 'extensions' subfolder of your profile folder
    (You can find your profile folder under Help->More Troubleshooting Information)
5. Go to Add-ons and Themes->gear (on the top right)->Install Add-on From File

[tbsortfolders.zip](https://github.com/protz/Manually-Sort-Folders/files/7080237/tbsortfolders.zip)

Again, this is an unofficial version. Any reports are welcome :-)

**Comment by mms1406** [comment]
Thanks a lot. It works!

**Comment by BillH99999** [comment]
I tried sorting accounts, sorting folders, and setting a default startup folder and all are working great. 

Thanks!
Bill

**Comment by itagagaki** [comment]
Thanks for the good report.
Jonathan has just submitted 2.1.0 to [ATN](https://addons.thunderbird.net/addon/manually-sort-folders/) .
It should be available soon :-)

**Comment by fightuntilwedie** [comment]
It works flawlessly. THANK YOU!

**Comment by itagagaki** [comment]
Version 2.1.0 is now available on [ATN](https://addons.thunderbird.net/addon/manually-sort-folders/) .

**Comment by BillH99999** [comment]
Thanks for all the hard work.  The extension is working great.  I have one observation.  Don't take this the wrong way it is just a suggestion of something that I'm not sure you are aware of or not.

In TB 91 extensions are now putting a wrench icon on the "Manage Your Extensions" page to allow people to set their options for the extension there rather than using the Tools menu.  It would probably be a good idea if MSF did it that same way for consistency.  

This is just a thought.  I have no problem with the way it is now.  

Thanks again,
Bill

**Comment by itagagaki** [comment]
@BillH99999 Thanks for the report and a suggention. If there is an opportunity for the next update, I will consider it.
