### ISSUE TITLE
MSF not working

### ISSUE THREAD

**Issue by 47Dgo** [protz/Manually-Sort-Folders#160]
Hello. I just installed this for Thunderbird 91 on Windows 10. but when clicking 'Manually sort folders' in the Tools menu, I get a window without any accounts or folders to select.  Others have also reported the same problem.

**Comment by skjerns** [comment]
Is there a reason to use 91, and not the most recent stable version 78.13.0?

**Comment by itagagaki** [comment]
duplicate of issue #159
