### ISSUE TITLE
Preferences Freezes Program

### ISSUE THREAD

**Issue by keithwjones** [protz/Manually-Sort-Folders#163]
Thunderbird 91.1.0 (64-bit) Win 10 21H1

When you enter Preferences the whole program freezes.

Keith

**Comment by itagagaki** [comment]
I've tried open Advanced Preferences on Thunderbird 91.1.0 (64-bit) Win 10 21H1 with MSF 2.1.0
but the freeze is not reproduced. It seems working fine.

Can you try Ctrl+Shift+J to see if it opens the error console?
If it does, look for a message that might indicate a problem.

**Comment by keithwjones** [comment]
Thank you for quick reply. I have removed all addons but now Thunderbird is not happy at all.

Before in Safe Mode everything was working. Now it is crashing so was better with your addon except when going to Preferences.

Errors:
Unexpected event profile-after-change URLQueryStrippingListService.jsm:224
Unknown Collection "thunderbird/query-stripping" RemoteSettingsClient.jsm:160
[Exception... "Favicon at "https://start.thunderbird.net/favicon.ico" failed to load: Not Found."  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource:///modules/FaviconLoader.jsm :: onStopRequest :: line 253"  data: no] FaviconLoader.jsm:253:22
XHRGEThttps://osbloggery.blogspot.com/feeds/4698984766729864924/comments/default
[HTTP/3 404 Not Found 536ms]

XML Parsing Error: mismatched tag. Expected: </link>.
Location: https://osbloggery.blogspot.com/feeds/4698984766729864924/comments/default
Line Number 9, Column 124:

Warnings:
[l10nregistry] Attempting to synchronously load file
            resource://gre/localization/en-GB/messenger/otr/otrUI.ftl while it's being loaded asynchronously. L10nRegistry.jsm:597:19
services.settings: thunderbird/hijack-blocklists has signature disabled RemoteSettingsClient.jsm:1027
Some cookies are misusing the recommended “SameSite“ attribute 2
feeds: downloaded: updates disabled due to error, check the url - https://osbloggery.blogspot.com/feeds/4698984766729864924/comments/default

Keith

**Comment by itagagaki** [comment]
I can't say for sure, but it looks like a problem with Thunderbird itself, so I recommend reinstalling Thunderbird (after uninstall it once).

Your profile will not disappear. You can check the name of your profile folder in `Help`->`More Troubleshooting Information` before you uninstall Thunderbird. Then, after reinstalling Thunderbird, do not start it right away, but run `thunderbird -p` from the command prompt. Alternatively, you can open the properties of the shortcut to start Thunderbird and add `-p` to the end of `...thunderbird.exe"` set there. Then you can select the profile you just checked.

**Comment by keithwjones** [comment]
I have put manually sort folders back on. Thunderbird re-installed.

Back to original problem:
Freezes every time I try to access Preferences.
OK in Safe Mode.

**Comment by wsmwk** [comment]
@keithwjones are you using a non-en-US locale with a language pack installed?

**Comment by keithwjones** [comment]
> @keithwjones are you using a non-en-US locale with a language pack installed?

Not sure how to check that.

Download was English (British)

**Comment by keithwjones** [comment]
Looks as though the problem could be:
English (GB) Language Pack which I have now removed.

**Comment by keithwjones** [comment]
It's known issue that only happens if you have a non-US locale, AND also have installed a language pack.
Might be a couple weeks until it's sorted out.

Thanks for the help. 

Keith
