### ISSUE TITLE
Error: undefined entity

### ISSUE THREAD

**Issue by MiecioWalti** [protz/Manually-Sort-Folders#165]
Hi peolple
Windows 10
Thunderbird 7.8.14.0 ( 32-bit )
Manually sort folders 2.1.0 
 
Error :
XML Parsing Error: undefined entity
Location: chrome://tbsortfolders/content/tbsortfolders.xhtml
Line Number 93, Column 13:
            <menuitem value="3" label="&sortmethod.alphabetical.descending;" />
------------^

how to solve?
Thanks

**Comment by itagagaki** [comment]
Thanks for the report.
I will investigate why it did not work on your environment.
