### ISSUE TITLE
Doesn't work anymore after thunderbird 91 upgrade

### ISSUE THREAD

**Issue by maxcuttins** [protz/Manually-Sort-Folders#169]
:(

**Comment by ABetch** [comment]
I got the same situation. 
Once the setting of Folder Pane Order modified, the effect is retained until reboot Windows.
Version : 91.3.1 / Add-on : 2.1.1

**Comment by itagagaki** [comment]
@ABetch Are you saying that if you reboot Windows, the order of the folders will revert to the way they were before you sorted them?
If so, it's strange.

**Comment by ABetch** [comment]
I'm sorry, I was wrong that restarting Windows will restore the folder order. 
However, I can confirm the symptom that the order of folders reverts back to the original order after some trigger.
This has occurred several times in the past few weeks.
The information in the configuration screen is still there, just need to click the "Update Folder Pane" button.
I'll report back when I've identified the trigger.

**Comment by itagagaki** [comment]
No new report came on this issue for a long time. So I will close this.
