### ISSUE TITLE
Slow to start

### ISSUE THREAD

**Issue by ThePianoGuy** [protz/Manually-Sort-Folders#17]
The add-on worked as advertised, but caused Thunderbird to take an extra 43 seconds to start.  During this time Thunderbird used 13% of an otherwise idle CPU, an extra ~30MB of RAM, and did not read or write to the hard drive.

I'm using Thunderbird 12.0 on Windows 7 and disabled the other addons to confirm it was this one exhibiting the behaviour.

I don't have an urgent need for this to be fixed but if you have some quick suggestions I'd appreciate it :)

**Comment by wsmwk** [comment]
@ThePianoGuy 
Do you still see this issue when using a current version of Thunderbird?

**Comment by wsmwk** [comment]
Not actionable without more information.  If you have more information about success or failure please add a comment.
