### ISSUE TITLE
Bug:  TB v91.5.0 "forgets" occasionally (after exit+re-start) folder order set by MSF v2.1.1 

### ISSUE THREAD

**Issue by pstein** [protz/Manually-Sort-Folders#171]
As I observed 64bit Thunderbird Portable v91.5.0 (maybe the previous versions too) on 64bit Windows forgets sometimes (but not always) the sort order of folders set by MSF v2.1.1.

When I exit TB and re-start it later the folder sort order is (sometimes) as initially (not necessarily alphabetically; But Inbox is always first)
Then I always have to call menu

Tools--->Manually sort folder

and simply click "Refresh folder pane" on Tab "Sort folders" to re-establish my own defined folder order.
So MSF does remember the customized folder order but TB does not remember it.
Maybe TB overrides it on certain events.

As far as I can see it happens when I exit & restart Thunderbird (but NOT always).
During TB sessions it is always kept.

By the way: The sequence of accounts is (always) kept.

**Comment by itagagaki** [comment]
Thank you for reporting. I'll investigate it.

**Comment by itagagaki** [comment]
Could you please uninstall MSF and install the version attached here and see how it goes for a while?

[tbsortfolders20220122.zip](https://github.com/protz/Manually-Sort-Folders/files/7918133/tbsortfolders20220122.zip)

And if the issue no longer seems to be occurring after a sufficient number of days, it would be helpful if you could report it here.

**Comment by pstein** [comment]
Ok, installed. Thank you.
I will tell you in 2 or 3 weeks if I can see an improvement

**Comment by Enkidu70** [comment]
Today I recognized that MSF obviously did not sort my folders. (Using latest TB on Linux Mint 20.3 Cinnamon.)
Second thing, there was no tools menu entry any more.
So I found this issue and installed zip/xpi above.

Now all seems to be back to normal.
Also tools menu entry is back.

Just one hint:
1. Remove old addon + RESTART
2. Install new downloaded addon + RESTART
(Removing it and installing the same time just removed it.)

**Comment by itagagaki** [comment]
@Enkidu70 Thanks for the report. I'm glad to see that this fix may be effective.
I'll keep an eye on it for a while longer, and if everything is better, I'll reflect on it in the next release.

**Comment by pstein** [comment]
Just want to confirm that the bug didn't happen again since I installed the new version.
So it looks good so far.
I suggest  to merge it into official version.
Thank you

**Comment by itagagaki** [comment]
@pstein That's good news! I will merge this fix.
Thank you!

**Comment by itagagaki** [comment]
MSF 2.1.2 is now available at addons.thunderbird.net. Please try it out.

**Comment by itagagaki** [comment]
No new report came on this issue. So it is considered to be resolved and is closed.
