### ISSUE TITLE
Sort not working in compact view

### ISSUE THREAD

**Issue by Danno59** [protz/Manually-Sort-Folders#172]
Hi
After manually sorting folders, they show up correctly except under compact view.
Can this be looked at.
TB version 91.5.0 (64-bit)

**Comment by itagagaki** [comment]
Duplicate of #65 ?

**Comment by itagagaki** [comment]
@Danno59 Don't you have any additional info?

**Comment by itagagaki** [comment]
The issue is unclear, so close it.
