### ISSUE TITLE
Active Tab Not Visible - macOS

### ISSUE THREAD

**Issue by 2BeeOrNot** [protz/Manually-Sort-Folders#173]
Text on the active tab on macOS is not visible and there is a lot of padding on the left side of the text. I added this to tbsortfolders.css:

 `@supports (-moz-osx-font-smoothing: auto) { /* macOS only */`
  `/* selected tab is white text on white background */`
  `tabbox tabs tab[visuallyselected="true"]:not(:-moz-window-inactive) { color: unset !important; }`
  `/* this pushes the tab label to the right of left side of tab */`
  `.tab-middle.box-inherit { display: none !important; } `
`}`

The active text is now visible and the left padding is gone.
Thanks for Manually-Sort-Folders.
macOS 12.2 / TB 91.5.1 / MSF 2.1.1

![MSF macOS 1](https://user-images.githubusercontent.com/63317977/151679424-e7842a50-e201-44a6-b10e-27032733cf0a.jpg)

![MSF macOS 2](https://user-images.githubusercontent.com/63317977/151679435-17b84b5f-9d46-470b-9b98-251673de317f.jpg)

**Comment by itagagaki** [comment]
Thanks for the fix, I didn't know there was such a problem with MacOS.
I'll consider incorporating it into the next release.

**Comment by itagagaki** [comment]
MSF 2.1.2 is now available at addons.thunderbird.net.
It contains corrections that you contributed.
Please try it out.

**Comment by itagagaki** [comment]
Since there seem to be no bad reports about this fix, this issue is closed.
Thanks to @2BeeOrNot
