### ISSUE TITLE
Feature Request : hide mailbox

### ISSUE THREAD

**Issue by n-rodriguez** [protz/Manually-Sort-Folders#178]
Hi there! Is it possible to have such a feature? A simple checkbox to show/hide the mailbox account in the main view? Just like sorting... but for hiding :smile: 

The use case is : I go on vacation, I've disabled IMAP checks in Thunderbird and so on for my professional mailbox. I also want to hide it from the main view until I go back from vacation :smile: 

Thank you!

**Comment by itagagaki** [comment]
You want to disable or hide your account while keeping it. Intuitively, it looks like it would be better to create that as a separate add-on.

I may try that someday if I feel like it.
(Don't hold your breath too much.)

**Comment by n-rodriguez** [comment]
> Intuitively, it looks like it would be better to create that as a separate add-on.

I agree, but since you're already "playing" with the mailbox tree in the main view I thought it would be a breath (at least for you) to do it in this addon :)

**Comment by itagagaki** [comment]
Unfortunately, it is not possible to hide a specific account from the folder tree view with an add-on.
Please make a request to Thunderbird itself.
