### ISSUE TITLE
folders list pane

### ISSUE THREAD

**Issue by iamcdash** [protz/Manually-Sort-Folders#18]
would like to see a toggle so i can display all folders or just marked folders
eg

instead of displaying
inbox 
drafts
sent
junk
trash
myname1
   mysubname 1
   mysubname 2
myname 2
myname 3

i could tag inbox, drafts, sent, myname 1, mysubname 2, & myname 3 and see

inbox
drafts
sent
myname 1
   mysubname 2
myname 3

would save a bunch of scrolling of the folders list pane.
either that or expand the folders list pane into multiple columns when it gets more than a page long

**Comment by wsmwk** [comment]
As noted in previous comment, sounds like this would not be a good feature match to this addon, so closing.
