### ISSUE TITLE
No longer possible to sort local folders? (TB 68.12.1)

### ISSUE THREAD

**Issue by JayceyF** [protz/Manually-Sort-Folders#184]
This add-on no longer works correctly when sorting accounts (although it used to!).  I happily used it for ages until my Thunderbird crashed.  I reinstalled my preferred version (68.12.1 - I have no desire for the newer ones) and now this feature no longer works.  (I have tried the main add-on and every version on Github.)

To explain more fully, what I want to do is place a local folder at the top of my account list in the left-hand main pane, so I see it first. This was always possible to do, but now it no longer works.

**'Sort Accounts' tab**
- 'Local Folders' is shown in a small separate box underneath all the other accounts (left-hand list), and is not clickable, therefore it cannot seemingly be moved (although the text confidently tells me that I can override this).
- The local folder that I actually created isn't shown at all in the left-hand list?
- I can see and set my folder in _First account in the folder pane_. but that does not work either (after restarts) - the folder stays firmly at the bottom of the list in the main pane.  (So I can't 'override this' then!)

**'Extra Settings' tab**
- In _Startup folder_, I can allegedly make my folder the Startup folder.  Yes, Thunderbird will go straight there on startup - but the folder is still at the bottom of my left-hand main pane!

I thought a workaround for this might be to make my folder a sub-folder inside 'Local Folders' - but if 'Local Folders' can't be moved anyway, what is the point?

What is so frustrating about this is that this feature USED to work - and it doesn't any more! If I'm using the same version (and the same version of Thunderbird that I used before), what is the problem - _why doesn't this work?_ 🤷🏻‍♀️

**Comment by itagagaki** [comment]
The add-on is working fine with TB 91.9.0 on my end.
Does that have anything to do with #162 ?
Because it is 68.12.1 there, too.

**Comment by JayceyF** [comment]
> The add-on is working fine with TB 91.9.0 on my end. Does that have anything to do with #162 ? Because it is 68.12.1 there, too.

Thank you for that - I will try your suggestions there and see what happens. 👍🏼

**Comment by JayceyF** [comment]
Hi @itagagaki, this is what I get when I do what you suggested in the other thread (I had already downloaded tbsortfolders@xulforum.org2.xpi from Github):

> 1653408519009	tbsortfolders.folderPane	DEBUG	Init
> 1653408519009	tbsortfolders.folderPane	DEBUG	Add observer
> WebExtensions: Loading chrome://localfolder/content/tabmanager.js implementation.js:786
> Tue May 24 2022 17:08:39 GMT+0100 (British Summer Time) CH: Current logLevel: 3
> xpunge - xpunge_ti_onWindowLoad (on Window #1): Tue May 24 2022 17:08:39 GMT+0100 (British Summer Time)

I don't appear to have a line that says 'Startup folder'?  (And only two that say DEBUG.)

However, I'm not sure if this is really the issue.  MSF is behaving itself when I select the Startup folder - my problem is that I can't _move_ my chosen folder (if I select it as the Startup folder, it stays at the bottom of the account list - TB obediently goes straight to it, but it's just in the wrong place).  This is a screen dump of what I see when I now go into MSF (any version):

![MSF](https://user-images.githubusercontent.com/106077723/170086283-33473249-63ba-4a0a-926d-fb88079a9e9d.jpg)

The folder I want to move to the top is called FILE CABINET - as you can see, I've selected that folder as the default account, which is supposed to put it at the top of the list - this does not happen, and THAT is my problem.  I have tried every available version of MSF, but I get the same result every time after numerous restarts - FILE CABINET stays firmly at the bottom of the list.  Exactly the same thing happens if I try and use 'Local Folders' as the default - nothing.  (What is so frustrating is that this USED to work, but now it doesn't!)  Do you have any more suggestions please?

**Comment by itagagaki** [comment]
"FILE CABINET" appears to be added as an account, not as a folder. How did you add it?

**Comment by JayceyF** [comment]
> "FILE CABINET" appears to be added as an account, not as a folder. How did you add it?

Sorry for the delay (I have Covid!).  This is what I did:-

_Tools > Account Settings > Account Actions > Add Local Folder_ (then I just filled in the dialogue box that appears, and submitted it - the new folder appears at the bottom of the left-hand list).

(I've made a few test folders using the above process, but they behave in the exact same way as FILE CABINET, as per above,)

As far as I see, this process is the only one available to create new local folders?

**Comment by itagagaki** [comment]
"Add Local Folder" is not present in Thunderbird 68.12.1 win64 en-US that I have tried.
![image](https://user-images.githubusercontent.com/71218184/170725058-87f863dd-f03b-4a4f-b12f-bdb2af823bc5.png)

What version do you have?

Or have you rewritten your pref.js file or used some add-on?

**Comment by JayceyF** [comment]
> "Add Local Folder" is not present in Thunderbird 68.12.1 win64 en-US that I have tried. ![image](https://user-images.githubusercontent.com/71218184/170725058-87f863dd-f03b-4a4f-b12f-bdb2af823bc5.png)
> 
> What version do you have?
> 
> Or have you edited your pref.js file or used some add-on?

I also have 68.12.1.  This is what I see in my Account Actions:-

![image](https://user-images.githubusercontent.com/106077723/170767104-394e9d72-c249-46d2-bc9c-cc40162ae966.png)

However... I DO use an add-on - I just checked!  It's called 'LocalFolders' - and I'd forgotten all about it? 🤦🏻‍♀️  (You can find out more about it here:- https://github.com/cleidigh/Localfolder-TB.)  It's such a good little tool that I suppose I'd forgotten that it was even an add-on!

Having said all that - the folder sorting _did_ use to work with 'LocalFolders', until my TB crashed and I had to reinstall it (even though I reinstalled 68.12.1).  I wonder if this glitch might be due to an update?  (I suppose I could delete it and try an older version.)

I assume that because I am using another add-on that you may not wish or be able to help me - and I would quite understand that.  (But it would be really interesting to know why your app suddenly stopped working in the way it did before!)

**Comment by itagagaki** [comment]
Okay, this issue is duplicate of #114 
This bug in Thunderbird has recently been fixed. I am not sure from which version, but at least it is fixed in 91.

And since 91, it is now possible to sort mail accounts and local folders in the same line.
So the "First account in folder pane" item in MSF is also gone.

I know you continue to use TB 68 for some other add-on compatibility or other reason, 
but I would recommend updating it if you can because of security issues.
