### ISSUE TITLE
Error if I use version 2.2.0

### ISSUE THREAD

**Issue by Jekl28** [protz/Manually-Sort-Folders#188]
If I start addon version 2.2.0 I have error:
"Ошибка синтаксического анализа XML: ошибка обработки ссылки на внешнюю сущность
Адрес: chrome://tbsortfolders/content/tbsortfolders_91.xhtml
Строка 7, символ 63:
<!DOCTYPE window SYSTEM "chrome://tbsortfolders/locale/ui.dtd">
--------------------------------------------------------------^"

Version addon 2.1.2 not have this error.

Version my Thunderbird is 91.11.0 (64-bit) russian portable. (In previous versions the same)
Operation system is Windows 10 Pro 1909 64-bit

**Comment by itagagaki** [comment]
Fixed.
ATN will be releasing 2.2.1 soon.
You can also download and install it from the following link.

https://github.com/protz/Manually-Sort-Folders/releases/download/v2.2.1/tbsortfolders.xpi

Sorry for inconvinience.
