### ISSUE TITLE
Select folder isn't displayed if thunderbird needs to scroll to get there

### ISSUE THREAD

**Issue by ThosRTanner** [protz/Manually-Sort-Folders#191]
I have a lot of folders (and several accounts) - as of thunderbird 102.4, if the folder configured for selection on startup isn't visible, thunderbird doesn't scroll to it and you have to find it manually.

**Comment by itagagaki** [comment]
It is a specification of Thunderbird. It seems difficult to improve it with add-ons.
But I'll look into it to see if I can do something about it.

**Comment by itagagaki** [comment]
It was a bug. A fixed version will be released soon.

**Comment by ThosRTanner** [comment]
Thank you!

**Comment by itagagaki** [comment]
I believe this bug has been fixed in MSF version 2.2.3, so I am closing this.
