### ISSUE TITLE
Slider missing in folder selcetion area in the settings window

### ISSUE THREAD

**Issue by OneMoreThomas** [protz/Manually-Sort-Folders#194]
Plugin V2.2.6, Thunderbird 102.5.0 

The list of folders is quit narrow, one can't identifiy the folder to shift. That does not matter - usually - due to the slider at the bottom of the list ... if I want to sort accounts. This slider is missing in the folder list: see picture.

Do I something wrong?

Kind regards,
Thomas.

![ManuallySortFolders - Bug](https://user-images.githubusercontent.com/121790221/210208145-80fe3eae-92a0-4d6e-8c70-fe0ea58a5944.png)

**Comment by itagagaki** [comment]
It is indeed narrow. It should be a bit wider in its default state... Anyway, try dragging the edge of the window to change the width.

**Comment by OneMoreThomas** [comment]
... Jesus - a level 8 failure ... how stupid!

Thanks for helping me to cross the street ;-))

Yours ...
