### ISSUE TITLE
No account re-ordering

### ISSUE THREAD

**Issue by bojan-liquity** [protz/Manually-Sort-Folders#197]
I am a long-time user and remember I was able to re-order my accounts.
Trying to do it now I do not see tis option, just ordering of folders. The description says there is a dedicated tab for accounts but I am not able to locate it.

Any pointers?

**Comment by itagagaki** [comment]
Here it is.
![image](https://user-images.githubusercontent.com/71218184/231613017-037269e6-0bf7-4679-8d36-cd1b2ebf14dc.png)

**Comment by bojan-liquity** [comment]
I do not see that.
<img width="593" alt="image" src="https://user-images.githubusercontent.com/73836320/231679268-c17ad3e6-26b9-4ccb-938d-fad1f7af9906.png">

**Comment by itagagaki** [comment]
Could you try this?
[tbsortfolders.zip](https://github.com/protz/Manually-Sort-Folders/files/11219276/tbsortfolders.zip)

**Comment by bojan-liquity** [comment]
Works, thx.
