### ISSUE TITLE
In TB24 the News & Blogs "account" sorts always last

### ISSUE THREAD

**Issue by gkarag** [protz/Manually-Sort-Folders#21]
And when I open Manually Sort Folders-> Sort accounts it stays on its original place. I would expect that it obeys the settings of the plugin.

Thanks for your work.

**Comment by xpavp03** [comment]
Still an issue in 31.6.0

**Comment by gkarag** [comment]
I tried the latest dev build on TB 45.2.0 and News & Blogs still sorts last, no matter how I sort it using the plugin preferences pane.

**Comment by protz** [comment]
Update: Thunderbird developers have committed to allowing sorting accounts (not folders) directly within Thunderbird, without the need for an addon. This will reuse some code that I (and others) wrote, which allows arbitrary reordering of accounts, meaning that this bug will be fixed automatically when the next version of Thunderbird comes out.

See https://bugzilla.mozilla.org/show_bug.cgi?id=244347 for a timeline and discussion.
