### ISSUE TITLE
TB 17.0.8 extremely slow in loading

### ISSUE THREAD

**Issue by newbino** [protz/Manually-Sort-Folders#24]
Hi, I have long used your extension - thanks! it has been great help - but now I am having problems.

My TB is very slow in loading: at first one can see only the folder pane, in 3 minutes + CPU climbs to 25% and Memory at start (from the usual 90k) climbs progressively to 550k+ until TB fully launches and then drops to about 150k

No problem with starting in Safe Mode, and all other addons I manually add don't create any problem until I enable to Manually Sort Folders.

In case it might be conflicting with another addon I add the screenlist. BTW if I diable or uninstall Toolbar Buttons, which is reported as incompatible with this version of TB, I keep on having the problem
![1](https://f.cloud.github.com/assets/5814009/1437287/d333c05c-416a-11e3-858d-dcc18c6d6a8a.PNG)
![2](https://f.cloud.github.com/assets/5814009/1437289/d6eea1b2-416a-11e3-9ef6-3e44ff253a71.PNG)

**Comment by wsmwk** [comment]
@newbino Do you still see this issue when using a current version of Thunderbird and add-on?

**Comment by wsmwk** [comment]
Not actionable without more information.  If you have more information about success or failure please add a comment.
