### ISSUE TITLE
Feeds fail to update at startup when set up as the default account

### ISSUE THREAD

**Issue by Parsnip** [protz/Manually-Sort-Folders#25]
Hey there.

I just sorted my accounts with the extension, moved the newsgroups & RSS feeds account on the top and set it up as the default "first account in the folder pane". When I do that, the feed account option "check for new articles at startup" stops working. Instead, when I start thunderbird the statusbar just says "null".

Using any email account as the top account will work just fine, it only seems to happen with the feed account.

**Comment by itagagaki** [comment]
@Parsnip Sorry, but I could not find the cause.
Currently, the latest version of Thunderbird is 91.0.3, and this add-on has been updated to version 2.1.0. Can you please update and try?

**Comment by Parsnip** [comment]
I haven't needed the addon for some time now and can't say if this is still an issue. Feel free to close the issue since no one else have reported it.
