### ISSUE TITLE
Descending alphabetical order

### ISSUE THREAD

**Issue by basille** [protz/Manually-Sort-Folders#27]
After a long time of using this very useful extension, I figured out that asking the question might save me some time: would it be possible to allow for a descending alphabetical order, from Z to A? 

In my case, I have a bunch of sub-folders that are named by starting date (e.g. '2014-01 Secret project'), which I then manually sort in descending order to have the most recent first. I also do the same in the Archive folder (one sub-folder per year).

However, this suggestion would only really make sense with a custom sorting of sub-folders, such as suggested [here](https://github.com/protz/Manually-Sort-Folders/issues/14).

Thanks, and keep up the good work!

**Comment by itagagaki** [comment]
Version 2.1.0 adds that feature. Please try it out.

**Comment by basille** [comment]
Thanks @itagagaki, I can see this in 2.1.0. However, this only works at the account level (i.e. all folders of an account behave the same)? In my case study, it really makes sense associated to the possibility to sort folders/subfolders differently. For instance, in a given account, default would be Thunderbird order, but then for a specific folder (e.g. Archive), everything in it would be reverse alphabetical (so as to get most recent years on top). Does that make sense?

**Comment by itagagaki** [comment]
Yes, it is. In the current spec, you can only choose the sorting method by account.
I'm not sure if the features requested in #14 or #153 will be achieved in the future, but if I can come up with a good way, I will try to contribute to it.

**Comment by basille** [comment]
Thanks for the confirmation @itagagaki, I appreciate it. #14 and #153 both imply independent sorting by folder (possibly with a default at the account level), and yes, that would be fantastic to have!
In the meanwhile, I can still fall back to full manual (which I often do) to get the exact sorting I want to have. Thanks for your work on MSF!
