### ISSUE TITLE
Yet another sorting problem

### ISSUE THREAD

**Issue by Binome-X** [protz/Manually-Sort-Folders#38]
Hi,
I've got 3 accounts: 1= local folders, 3=imap mails, 4=rss feeds
I can get 4,3,1 or 3,1,4 and I want 3,4,1 but I can't manage it (of course).
TB 31.4.0

**Comment by Binome-X** [comment]
No response?

**Comment by protz** [comment]
Inner Thunderbird limitation, not much I can do about it :(
