### ISSUE TITLE
not working with gmail, works with other account

### ISSUE THREAD

**Issue by gallusgiulio** [protz/Manually-Sort-Folders#40]
This addon works like a charm for my work email account, I've listed my IMAP folders exactly as I wanted and it's great. The issue comes with my gmail account: here, strangely enough, I'm not able to sort my folders; I'm only able to sort the sub-folders I've created. This is my gmail structure:

Inbox
[Gmail]
----Drafts
----Sent Mail
----Spam
----Trash
My Folder 1
My Folder 2
----My Subfolder 1
----My Subfolder 2
My Folder 3
----My Subfolder 3
----My Subfolder 4
----My Subfolder 5

The only folders I can sort are My Subfolders 1, 2, 3, 4, and 5, each one obviously within its parent folder.

Do you have any idea why this could happen? Thanks for your support.

**Comment by wsmwk** [comment]
@gallusgiulio 
Do you still see this issue when using a current version of Thunderbird and add-on?

**Comment by itagagaki** [comment]
It's been quite some time now, and I'm sure things have changed, so can I close this issue now?

**Comment by itagagaki** [comment]
We have not received any reports that this issue has been resolved. But I consider this is obsolete. So I will close this.
