### ISSUE TITLE
Automatically sort by date

### ISSUE THREAD

**Issue by jean2** [protz/Manually-Sort-Folders#44]
Hi,

This is a feature request.
I was looking for an extension that automatically sort the folders by date of last received message in the folder. There is a lot on the Internet about sorting the messages in the folder, but I want to sort the folder themselves. This extension is the closest I could find.
Thanks in advance !

Jean

**Comment by protz** [comment]
I think this is the "View > Folders > Recent" feature of Thunderbird (in
the menus).

Please close this issue if that answers your question.

Cheers,

~ jonathan

**Comment by jean2** [comment]
Woah, this feature is well hidden. It took me a while to find it. Thanks for the hint.
It looks to me that "recent" is the most recently read folders, not the folders where the most recent message were read. I'll need to experiment a bit more.
Thanks a lot !

Jean
