### ISSUE TITLE
eXquilla folders

### ISSUE THREAD

**Issue by iamcdash** [protz/Manually-Sort-Folders#46]
I have recently started using eXquilla as my university is no longer supporting imap access to their exchange server.

manually sort folders does not seem to recognize eXquilla folders.
i asked them:
     i have 2 exquilla accounts and 3 non-exquilla accounts
     i can make one exquilla account the default so it appears first, but the other exquilla account is always listed  last
      how can i move it to before my gmail accounts???

eXquilla responded 
     There is no support in default Thunderbird to change account order, but there is a popular addon for this: https://addons.mozilla.org/en-US/thunderbird/addon/manually-sort-folders/ I don't know if this works with ExQuilla though.

**Comment by skyline11** [comment]
Add me to this feature request.  Manually sort folders doesn't allow ExQuilla accounts to be sorted - they are either at the bottom of the list, or one can be chosen as the default account and appear first.  Neither position suits in my case.

**Comment by b1u3scr33n** [comment]
Add me aswell (like skyline11). Just started using ExQuilla.
I would be curious about an extension that supports and lists these email accounts aswell.

My "ExQuilla" Account appears at bottom of the list. regardless how i order the others via "ManuallySortFolders"

**Comment by kiravi** [comment]
Would love to have exquilla in sort sequence. 

As of  1.2.0 it does not appear in ability to sort account.

**Comment by ovari** [comment]
Can this issue be closed as a patch has been merged? Thank you

**Comment by ovari** [comment]
Does the patch also work for [Owl for Exchange](https://addons.thunderbird.net/addon/owl-for-exchange/)? Both add-ons are now developed/maintained by https://www.beonex.com/

**Comment by wsmwk** [comment]
> 
> 
> Does the patch also work for [Owl for Exchange](https://addons.thunderbird.net/addon/owl-for-exchange/)? Both add-ons are now developed/maintained by [Beonex](https://www.beonex.com/).

I would think "no".  https://bugzilla.mozilla.org/attachment.cgi?id=9085417&action=diff suggests "exchange" account type is needed.  File a new issue?

But this issue should be closed.  @protz
