### ISSUE TITLE
How do I stop Sent mail from displaying in the email list?

### ISSUE THREAD

**Issue by JimInSanDiego** [protz/Manually-Sort-Folders#47]
I installed the newest version of **_Manually-Sort-Folders v1.1_** this morning into **_Thunderbird v38.7.1_**.  I can now change the order of items in the left column but Sent mail is being displayed in the right side email list.  It has cluttered the list.  Is there a way to turn off the display of Sent mail?

Thanks,  James

**Comment by protz** [comment]
I'm not sure I understand what you mean. Care to provide a screenshot?

**Comment by JimInSanDiego** [comment]
I have attached a screenshot.  Notice that Sent mail is listed under the 
Location column.  My Inbox is a combined Inbox.  If I select an 
individual email account, the sent mail doesn’t display.

**Comment by protz** [comment]
You need to use the github web interface to post pictures. 
Comment-via-email doesn't allow you to do that.

**Comment by JimInSanDiego** [comment]
Here is the screenshot.
![screenshot 2016-03-28 09 04 59](https://cloud.githubusercontent.com/assets/9100662/14089200/84acc6d4-f4e8-11e5-9739-ee5455ab1aa0.png)

**Comment by protz** [comment]
You can click on the tiny symbol right right above the scrollbar to 
choose which columns to display.

**Comment by JimInSanDiego** [comment]
Ok, that was a simple option that my brain cells missed.  Thanks.  May I assume if the Location column is displayed then Sent emails will always be included?

Thanks,

James

**Comment by protz** [comment]
That's because you're using a unified inbox. Right-click on Inbox, 
Properties, then Choose.

**Comment by JimInSanDiego** [comment]
Thanks again,

James

**Comment by JimInSanDiego** [comment]
On Second Thought:

I've attached the image from yesterday but with annotations today.  Yes I can choose whether the Location column is displayed or not but that isn't what I want to disappear.  I only want to see Inbox emails listed and I don't want Sent emails listed.  In other words, when I look at my list of emails, all I want to see is Inbox emails.  Is there a way to stop listing Sent emails?
![screenshot 2016-03-28 09 04 59](https://cloud.githubusercontent.com/assets/9100662/14108485/910f40a2-f572-11e5-8ba5-d8ae1a8464a1.png)

**Comment by protz** [comment]
That's because you're using a unified inbox. Right-click on Inbox, 
Properties, then Choose.

~ jonathan
