### ISSUE TITLE
No entry in tools menu

### ISSUE THREAD

**Issue by Jazzin** [protz/Manually-Sort-Folders#50]
I've just installed this add-on in thunderbird 45.4.0. I then struggled to find the "Manually sort folders" option in the tools menu. It turns out it is only in the tools menu in the menu bar. Not in the tools menu found by clicking on the three line "Display the Thunderbird Menu" button on the right. It really ought to appear in both menus to avoid any confusion. I don't normally have the menu bar enabled, so didn't initially think to look there.

Thanks

Andy

**Comment by wsmwk** [comment]
This is issue #22. Closing
