### ISSUE TITLE
alphabetically sub-folders

### ISSUE THREAD

**Issue by MrGlasspoole** [protz/Manually-Sort-Folders#51]
Hi, i use your extension since a long time but have one problem.
The problem is that i have hundreds of folders and its a pain to sort them by hand.
Its cool i can sort the main folders how i want them, but it would be nice if there
would be something in the context menu for sub-folders like "sort alphabetically".

**Comment by itagagaki** [comment]
Added the button. Hope you like it.
The new version 2.2.0 has been also available on ATN.
