### ISSUE TITLE
worked like a charm yesterday -acting weird today

### ISSUE THREAD

**Issue by robin1232** [protz/Manually-Sort-Folders#53]
First, I've used this add-on for ages on the PC and now on the Mac and it's always worked beautifully - thank you so much for that.  Today, the theme from the Twilight Zone is playing in the background.
When I manually sort folders, everything appears in the correct order, but when I view my email, the accounts in the navigation pane to the left are not appearing in the specified order.  I've tried disabling it and re-enabling it but no go.  Next step is to uninstall and reinstall.  Have you seen this before?  Thank you for any help you can provide.

![manually sort folders](https://cloud.githubusercontent.com/assets/24546372/21142689/5f450eec-c111-11e6-8a5d-cef2728bb895.png)

**Comment by Gluups** [comment]
Hello,

       I once had a problem with one of the tabs of the extension that       did not work properly.
       This is how I went to subscribed the newsletter. Perhaps a forum       would have been a more appropriate support ?

       I do not remember exactly how much time that took, but now       everything works OK. I admit I do not change the order very       frequently.

       On 13rd Dec. 2016 at 14:48 UTC + 2, robin1232 wrote :

First, I've used this add-on for ages on the PC and now on the         Mac and it's always worked beautifully - thank you so much for         that. Today, the theme from the Twilight Zone is playing in the         background.
         When I manually sort folders, everything appears in the correct         order, but when I view my email, the accounts in the navigation         pane to the left are not appearing in the specified order. I've         tried disabling it and re-enabling it but no go. Next step is to         uninstall and reinstall. Have you seen this before? Thank you         for any help you can provide.       

-

**Comment by wsmwk** [comment]
@robin1232 do you still see this when using a current version ?

**Comment by itagagaki** [comment]
@robin1232 @Gluups  It's been quite some time now, and I'm sure things have changed, so can I close this issue now?

**Comment by itagagaki** [comment]
We have not received any reports that this issue has been resolved. But I consider this is obsolete. So I will close this.
