### ISSUE TITLE
Putting RSS on top of the account list breaks "check new articles at startup" option

### ISSUE THREAD

**Issue by Parsnip** [protz/Manually-Sort-Folders#56]
Putting the RSS feed on top of the sort accounts window works great visually, but doing that breaks the "check for new articles/messages at startup" option on all accounts.

**Comment by wsmwk** [comment]
@Parsnip 
Do you still see this issue when using a current version of Thunderbird?

**Comment by Parsnip** [comment]
I've stopped using the add-on sometime between then and now so I don't know. Sorry.

**Comment by itagagaki** [comment]
@Parsnip If you don't need to solve this issue anymore, can I close this?

Note that Thunderbird is now version 91, and this add-on has been updated to 2.1.0. Please try it if you like.
