### ISSUE TITLE
Do not see folders in the manually sort folders list. Caused by  "invalid account" entry.  Workaround: remove account from mail.accountmanager.accounts

### ISSUE THREAD

**Issue by Gluups** [protz/Manually-Sort-Folders#57]
From time to time, somebody arrives here and tells, in the dialog box of "Manually sort folders", I see no folders, so I cannot sort them.
This happened to me, and I noticed something.
In the Tools menu, you have an Account Parameters entry.
In the dialog box opened with that, you have a list of accounts, on the left.
At the end of that list, I had an "invalid account" entry. This was account71.
After closing Thunderbird, I opened the profile folder, and there the prefs.js file in a text editor.
In the file I searched for account71, my invalid account. I found it in the line mail.accountmanager.accounts, and erased it from there, with the next comma.
After saving prefs.js I opened Thunderbird again, went to the Account Parameters dialog box again, and at the end of the accounts list, found an invalid account again, this time account73.
I made the same action in prefs.js than I did for account71.
I came back to Thunderbird, to the Account Parameters dialog box, and this time saw no invalid account.
Then, the Manually Sort Folders extension had the accounts list visible again in its dialog box.

**Comment by wsmwk** [comment]
@Gluups Do you still see this issue when using a current version of Thunderbird and add-on?

**Comment by wsmwk** [comment]
@protz, do you think this issue still exists based on aceman's comment on this issue?  

>  It looks like had some broken
> accounts that he removed from the list (but not completely from TB).
> We had such cases and updated the Account settings dialog to try
> {}catch() {} each account in case it throws due to some error so that we
> can recover and show that "invalid account" label the user describes.
> It may be the addon isn't prepared to get invalid/throwing accounts thus
> it fails to populate the account list.

**Comment by protz** [comment]
I'll have to take a look. I found out through another (unrelated) thread somewhere on the Thunderbird mailing lists that the presence of a default account is no longer guaranteed, which finally explains why we suddenly saw all of these failures pop up. I'm in the process of cleaning up and porting the addon to Thunderbird 72+ so I'll make sure I deal with that case, then will close this issue.

**Comment by Gluups** [comment]
Well, this works OK for me.
#116 has been closed, I imagine we can close this one also.
