### ISSUE TITLE
Keeps asking for restart -  Installation issue

### ISSUE THREAD

**Issue by zoltankatai** [protz/Manually-Sort-Folders#59]
I  use Thunderbird 52.4 ( in Hungarian ) and it is installed on  a USB stick as part of Portable apps.

![screenshot 317](https://user-images.githubusercontent.com/32808225/31582138-f48ef764-b17b-11e7-8bc4-74048ca67fa7.jpg)

I install this add-on, and then it asks for restart.

After the restart I get back the same screen ( asks for mark the authorisation to install the add on and restart )  I restart and get back to the very same screen. 

![screenshot 316](https://user-images.githubusercontent.com/32808225/31582134-dc9ce846-b17b-11e7-95a6-eba4a7e196d1.jpg)

When I check the add-ons, it shows, that it is disabled. When I try to enable it, it goes back the same screen, ( asking for restart )

![screenshot 318](https://user-images.githubusercontent.com/32808225/31582141-012c5552-b17c-11e7-9382-99043563a41e.jpg)

**Comment by wsmwk** [comment]
@zoltankatai Do you still see this issue when using a current version of Thunderbird and add-on?

**Comment by wsmwk** [comment]
Not actionable without more information.  If you have more information about success or failure please add a comment.
