### ISSUE TITLE
Define alphabetical sort order as default but allow customization for some folders?

### ISSUE THREAD

**Issue by bsto** [protz/Manually-Sort-Folders#61]
In general I would like to define the alphabetical sort sort order of folders (within an account) as default.

How do I do this (with Manually Sort Order)?
Resp. similarly: How do I define a sort order depending on the creation/last modified date (of containing messages)?

Beside these general rules I want to define for a few (sub)folders a different, indiviudal, customized order.

Is this somehow possible or is the unique folder sort order enforced to ALL (sub) folders of an account?

Maybe this feature could be added in the next versions of the AddOn

**Comment by protz** [comment]
I'm closing in favor of #87 -- the other requests (last creation date) seem like a narrow use-case that would require significant implementation work, so I'll pass on those. Thanks.
