### ISSUE TITLE
Doesn't work in v60.0b1 Windows 10-64

### ISSUE THREAD

**Issue by aquagenic** [protz/Manually-Sort-Folders#62]

**Comment by Gluups** [comment]
Hello,
As a user I have version 1.1.1 on Thunderbird 52.7.0, it works jolly good on Windows 10 64 bits (on 2 machines).

**Comment by protz** [comment]
I've bumped the default compatibility on the addons.mozilla.org website so that you can install it from within thunderbird. Please reopen if that doesn't work.
