### ISSUE TITLE
Blank Window(s) Unable to do anything

### ISSUE THREAD

**Issue by TeacherMac** [protz/Manually-Sort-Folders#63]
Thunderbird current version: 60.0b6 (32-bit)
Windows 10 ver 1803 Build 17134.81

Will this addin be working soon?

Thanks

**Comment by shiro** [comment]
Actually it works if you:
- downgrade to stable
- reorder the desired folders
- upgrade back to beta

Of course this is extremely tedious and a patch would be much appreciated.

**Comment by Bugzillaroid** [comment]
Account and Sort Folder windows were empty. Nothing worked, and received the following console error when trying to set options:

SyntaxError: missing { before function body  ui.js:361:42
ReferenceError: on_load is not defined[Learn More]  tbsortfolders.xul:1:1

**Comment by protz** [comment]
My sincerest apologies for the long delay with this update. Various life things got in the way, not to mention my research work which is my main focus of interest these days. I am happy to announce that, in spite of it all, this addon which I created while an undergrad nearly 10 years ago just received an update that makes it compatible with Thunderbird 60! Thunderbird should update automatically in a few days, as soon as my new version is accepted. If you'd rather upgrade now:

download the version from my website: https://jonathan.protzenko.fr/manually-sort-folders/manually-sort-folders-201812152042.xpi
then, in Tools > Addons, hit the cog, the do "install addon from file".
Thanks again to @Ximi1970 for the update.

Hope this helps!

Best,

Jonathan

**Comment by TeacherMac** [comment]
Hey Jonathan,

Thanks for the update however the file appears to be corrupted. I've 
attempted to download/install several times:



Thanks,

Greg
