### ISSUE TITLE
Feature Request: Folder Identity

### ISSUE THREAD

**Issue by Bugzillaroid** [protz/Manually-Sort-Folders#66]
Would like to be able to specify my identity on a per-folder basis. Want to be able to associate certain newsgroup folders with certain identities. Folder Identity add-on developer is no longer doing this, so need someone who is still doing active development.

**Comment by wsmwk** [comment]
@protz is this not out of scope for this add-on?

**Comment by protz** [comment]
This is out of scope, yes. I don't plan on adding any new features. Thanks for the triage!
