### ISSUE TITLE
Local Folders

### ISSUE THREAD

**Issue by Twinklebell** [protz/Manually-Sort-Folders#68]
I can't set Local Folders as the start folder. In fact, I can't access "Local Folders" at all.

Selecting a sort folder, or a starting folder on the tabs just selects nothing. Most odd.

I am using Thunderbird 60.0

**Comment by 76c72cfe** [comment]
Same here. No folder or accounts.  TB 60.0

**Comment by SeLLeRoNe** [comment]
Unfortunately it's the same here, I have also tried the Dev release

**Comment by protz** [comment]
My sincerest apologies for the long delay with this update. Various life things got in the way, not to mention my research work which is my main focus of interest these days. I am happy to announce that, in spite of it all, this addon which I created while an undergrad nearly 10 years ago just received an update that makes it compatible with Thunderbird 60! Thunderbird should update automatically in a few days, as soon as my new version is accepted. If you'd rather upgrade now:

download the version from my website: https://jonathan.protzenko.fr/manually-sort-folders/manually-sort-folders-201812152042.xpi
then, in Tools > Addons, hit the cog, the do "install addon from file".
Thanks again to @Ximi1970 for the update.

Hope this helps!

Best,

Jonathan
