### ISSUE TITLE
folders_tree.builderVew is undefined

### ISSUE THREAD

**Issue by vkrizan** [protz/Manually-Sort-Folders#69]
The plugin stopped working since TB version 60.0.

Here is the error message:
```
TypeError: folders_tree.builderVew is undefined  ui.js:198:3
	on_load chrome://tbsortfolders/content/ui.js:198:3
	onload chrome://tbsortfolders/content/tbsortfolders.xul:1:1
	oncommand chrome://messenger/content/messenger.xul:1:1
```

Thank you!

PS: I'll try to find how to fix it...

**Comment by hb9tst** [comment]
same as #67 (see comments there). The big issue is that XUL RDF-based trees do not exist anymore in TB 60, so this part of the UI has to be reimplemented otherwise. This is unfortunately not trivial to fix, unless having quite some insight about the internals of TB...

**Comment by vkrizan** [comment]
Thanks. I had prevision that the tree element in TB has changed. Unfortunately I have no experiences with the internals of Mozilla.

Closing, as it is ...
Duplicate of #67
