### ISSUE TITLE
Thunderbird 60+ version @Ximi1970

### ISSUE THREAD

**Issue by Ximi1970** [protz/Manually-Sort-Folders#73]
Hi all,

You can find my  @Ximi1970 patched Thunderbird 60 version here:

[v1.2.0pre3 - Thunderbird 60+ release](https://github.com/Ximi1970/Manually-Sort-Folders/releases/tag/v1.2.0pre3)

**Comment by rgruetzner** [comment]
Just tested this version. It works fine for me. Thank you very much for making this great utility working again!
Roland

**Comment by Der-Orso** [comment]
YIS!! Thank You!!

**Comment by bebabi34** [comment]
thanks. v1.2.0pre3 works on tb 60.2.1 on debian stable (stretch)

**Comment by gabri25ele** [comment]
thank you very much, you save our lifes

**Comment by mlipok** [comment]
Works fine on my 60.3.0 (32Bit) version

**Comment by mclaborn** [comment]
This did not work for me (Thunderbird 60.2.1 on Ubuntu) in the "Favourite Folders - Compact View". Is it expected to work there?

**Comment by anhdy41** [comment]
Thank you very much!  Works on TB 60.2.1 on 18.04

**Comment by Shitennouji** [comment]
Works fine on my Thunderbird 60.3.1 (64 bit) by Windows 10 1803

**Comment by schneeschmelze** [comment]
Same here on macOS 10.13.6.

**Comment by protz** [comment]
I'm closing this issue as Ximi's version has now submitted to addons.mozilla.org and will be rolled out as soon as it is approved. Once again, many thanks for the bugfix from @Ximi1970
