### ISSUE TITLE
Down/Up Arrows missing

### ISSUE THREAD

**Issue by dgo47** [protz/Manually-Sort-Folders#74]
The up/down arrows to enable folders to be moved seem to be missing!  

I am running a Windows 10 machine with Thunderbird 52.9.1 and your latest available version.  

What am I doing wrong?

**Comment by protz** [comment]
My sincerest apologies for the long delay with this update. Various life things got in the way, not to mention my research work which is my main focus of interest these days. I am happy to announce that, in spite of it all, this addon which I created while an undergrad nearly 10 years ago just received an update that makes it compatible with Thunderbird 60! Thunderbird should update automatically in a few days, as soon as my new version is accepted. If you'd rather upgrade now:

download the version from my website: https://jonathan.protzenko.fr/manually-sort-folders/manually-sort-folders-201812152042.xpi
then, in Tools > Addons, hit the cog, the do "install addon from file".
Thanks again to @Ximi1970 for the update.

Hope this helps!

Best,

Jonathan
