### ISSUE TITLE
No accounts or folders shown in preferences

### ISSUE THREAD

**Issue by mepat218** [protz/Manually-Sort-Folders#75]
TB 60.3.0 (32bit). Manually Sort Folders 1.1.1 Windows 10Pro
TB was recently updated to latest version. Since the update, Manually Sort Folders add on does not work. When I open the add on, I cannot see any of the accounts or folders listed in the drop down menu.
![msf - accounts](https://user-images.githubusercontent.com/45029464/48467798-f283f100-e824-11e8-9e3e-1b3669fbdc5f.JPG)
![msf - folders](https://user-images.githubusercontent.com/45029464/48467832-09c2de80-e825-11e8-8917-f057636796ad.JPG)

**Comment by Gluups** [comment]
Version 1.2.0pre3 is OK for Thunderbird 60.3.0 - 32 bits, on Windows 10 version 1803 - 64 bits.

**Comment by mepat218** [comment]
Where can I download Version 1.2.0? The latest version available on addons.thunderbird.net is 1.1.1

**Comment by Gluups** [comment]
Have a look there :
<https://github.com/Ximi1970/Manually-Sort-Folders/releases>

**Comment by mepat218** [comment]
Thanks for this. How do I go about installing?

![msf 1 2 0](https://user-images.githubusercontent.com/45029464/48480875-b3ff2e00-e846-11e8-9566-13e6999770b1.JPG)

**Comment by Gluups** [comment]
Well this is quite classical, first download the file, then from the extension manager (Tools / Addons) click on the button on top of the tab, then "install from a file" and select the file.

**Comment by mepat218** [comment]
Thank you!
