### ISSUE TITLE
Default folder on opening

### ISSUE THREAD

**Issue by frizzie55** [protz/Manually-Sort-Folders#76]
It seems the Extra Setting 'Startup Folder' is no longer working in Thunderbird 60.3, at least in combination with CCleaner. Before, after running CCleaner, Thunderbird opened in the selected 'Inbox' folder, now it just goes to the top email account. Whether I select 'Open last opened folder' or select one in 'Custom Folder'.

Not sure if it is a CCleaner thing or a Thunderbird thing.

**Comment by Webdongle** [comment]
Can confirm the add-on no longer works for selecting default opening folder.  Also the popup selection screen the close button doesn't work.

When Thunderbird updated ... it warned some add-ons would not work.  The add-on is no longer  compatible with Thunderbird.

**Comment by Webdongle** [comment]
I'm using Thunderbird 60.3.1 (32 bits) on Windows 10 1803 (64 bits), with version 1.1.1 of Manually Sort Folders.  Uninstalled and re added but no avail.  Where did you get 1.2.0pre3 from ?

**Comment by Gluups** [comment]
Oh yes version 1.1.1 is quite obsolete, please have a look there :
[https://github.com/Ximi1970/Manually-Sort-Folders/issues/5#issuecomment-438668871](url)
The official store was not update for the main developer had no time for it, we hope that will arrive soon.

**Comment by Webdongle** [comment]
OK worked it out

https://github.com/Ximi1970/Manually-Sort-Folders/releases/
Right click save as
Then in Thunderbird extensions click the gear icon and install from file.

Will the fork be given a name and be put in the extensions list ?

**Comment by Gluups** [comment]
Manually sort folders ;)
The name is localized.

**Comment by Webdongle** [comment]
So when the 'Manually sort folders' is updated will the fork v1.2.0pre3 recognise the update to v1.1.1 ?

**Comment by protz** [comment]
My sincerest apologies for the long delay with this update. Various life things got in the way, not to mention my research work which is my main focus of interest these days. I am happy to announce that, in spite of it all, this addon which I created while an undergrad nearly 10 years ago just received an update that makes it compatible with Thunderbird 60! Thunderbird should update automatically in a few days, as soon as the new version is accepted. If you'd rather upgrade now:
- download the version "1.2.0pre3" listed in the comments above, or from my website: https://jonathan.protzenko.fr/manually-sort-folders/manually-sort-folders-201812152042.xpi
- then, in Tools > Addons, hit the cog, the do "install addon from file".

Thanks again to @Ximi1970 for the update.

Hope this helps!

Best,

Jonathan
