### ISSUE TITLE
Folder pane list is empty

### ISSUE THREAD

**Issue by zkab** [protz/Manually-Sort-Folders#78]
I have TB 60.2.1 (64 bits) and Ubuntu 18.04 LTS.
The folder pane list is empty ...

**Comment by Gluups** [comment]
I presume you installed version 1.1.1 of Manually Sort Folders ?
Try this one :
https://github.com/Ximi1970/Manually-Sort-Folders/releases/tag/v1.2.0pre3
and do not forget to use the contextual menu to download, and then "install from a file" in Thunderbird.

In some cases a little older version is preferable, tell us the results.

@Xim1970 : Wasn't there a thread "How to Update" ?

**Comment by Gluups** [comment]
Yes, version 52 of Thunderbird requires version 1.1.1 of Manually Sort Folders, and version 60 of Thunderbird requires 1.2.0pre3
There has been a case where 1.2.0pre3 was not OK but 1.2.0pre2 was.
Everyone found his good version, did not he ?
It seems what remains to do is to situate the cases where a different version from 1.2.0pre3 is necessary. It would be nice if it was possible to create a version that detects the conditions and adapts itself.
And then of course, what would save much time, would be to deploy that version to the add-ons site of Mozilla.

**Comment by LeslieDesser** [comment]
The link above to 1.2.0pre3  worked just fine for me on Windows10.

**Comment by mhellmeier** [comment]
Same problem here on Ubuntu and Windows with Thunderbird 60.3.3. The manual update to _Manually Sort Folders_ version 1.2.0pre3 solved the problem.

**Comment by Gluups** [comment]
Please have a look there : 
[https://github.com/protz/Manually-Sort-Folders/issues/78](url)

**Comment by protz** [comment]
My sincerest apologies for the long delay with this update. Various life things got in the way, not to mention my research work which is my main focus of interest these days. I am happy to announce that, in spite of it all, this addon which I created while an undergrad nearly 10 years ago just received an update that makes it compatible with Thunderbird 60! Thunderbird should update automatically in a few days, as soon as my new version is accepted. If you'd rather upgrade now:
- download the version from my website: https://jonathan.protzenko.fr/manually-sort-folders/manually-sort-folders-201812152042.xpi
- then, in Tools > Addons, hit the cog, the do "install addon from file".

Thanks again to @Ximi1970 for the update.

Hope this helps!

Best,

Jonathan
