### ISSUE TITLE
Thunderbrid 63.0.3. no list with accounts

### ISSUE THREAD

**Issue by hanzelmannes** [protz/Manually-Sort-Folders#79]
there are no accounts visible in the 'Manually sort folders,  Window. The add-on those not work unfortionatly

**Comment by Gluups** [comment]
Maybe you installed version 1.1.1 of Manually Sort Folders ?
Please try one from there : 
https://github.com/Ximi1970/Manually-Sort-Folders/releases

**Comment by m333w** [comment]
> 
> 
> Maybe you installed version 1.1.1 of Manually Sort Folders ?
> Please try one from there :
> https://github.com/Ximi1970/Manually-Sort-Folders/releases

You solve my problem with the new version of thunderbird. Thx 👍

**Comment by fthommen** [comment]
1.1.1 is still the official release published on https://addons.thunderbird.net.  I am confused: Is this add-on not supported by the original author any more?

**Comment by kjodle** [comment]
> Maybe you installed version 1.1.1 of Manually Sort Folders ?
> Please try one from there :
> https://github.com/Ximi1970/Manually-Sort-Folders/releases

I had the same issue. Upgrading to the latest release solved it for me. (Ubuntu 18.04; Thunderbird 60.2.1 64-bit.)

**Comment by protz** [comment]
My sincerest apologies for the long delay with this update. Various life things got in the way, not to mention my research work which is my main focus of interest these days. I am happy to announce that, in spite of it all, this addon which I created while an undergrad nearly 10 years ago just received an update that makes it compatible with Thunderbird 60! Thunderbird should update automatically in a few days, as soon as my new version is accepted. If you'd rather upgrade now:
- download the version from my website: https://jonathan.protzenko.fr/manually-sort-folders/manually-sort-folders-201812152042.xpi
- then, in Tools > Addons, hit the cog, the do "install addon from file".

Thanks again to @Ximi1970 for the update.

Hope this helps!

Best,

Jonathan
