### ISSUE TITLE
Sorting lost on restart (60.5.0 for Mac)

### ISSUE THREAD

**Issue by jason-hub** [protz/Manually-Sort-Folders#83]
In Thunderbird 60.5.0 for Mac, sorting no longer applies after restarting TB.  Plus, all main account folders are collapsed after restarting.  I have to manually open and re-sort all folders.

To get my sorting back, I have to do the following every time I start TB: 

`Tools --> Manually sort folders --> Sort folders --> Refresh folder pane`

That instantly re-applies all of my sorting rules for all of my accounts and sub-folders.  Is there an available fix for this problem?

**Comment by protz** [comment]
I haven't experienced this. Any meaningful errors in Tools > Developer Tools > Error Console that might be related to "manually sort folders"?

**Comment by wsmwk** [comment]
Reporter @jason-hub appears to be gone, so closing this issue
