### ISSUE TITLE
nothing happens

### ISSUE THREAD

**Issue by catgil3** [protz/Manually-Sort-Folders#85]
I go to Tools > Add-on preferences > Manually sort folders and click. Nothing happens. I don't see any other paths to activating the add-on. I can't figure out how to open or use the tool. I've tried to open the prefs a number of times including after quitting and restarting Thunderbird.  
I'm on a mac using Thunderbird 60.7.2. 
Any help appreciated. Thanks!

**Comment by protz** [comment]
Have you tried hitting "Tools > Manually Sort Folders" in the menus?
