### ISSUE TITLE
Automatically Sort Accounts Alphabetically

### ISSUE THREAD

**Issue by etherija** [protz/Manually-Sort-Folders#87]
Hi,

I use Manually-Sort-Folders to arrange my accounts in alphabetical order. By default Thunderbird lists the accounts in the order they were added.

It would be great to add a button which automatically sorts the folders alphabetically, and would save me a lot of time.

*Bonus Points* have an optional setting which always checks/adjusts ordering on open/close/restart for accounts not in alphabetical order.

**Comment by selioss** [comment]
Hi,
I'm voting for this issue. An alphabetical sort for accounts could be great. Any news for this feature ?

**Comment by o0Julia0o** [comment]
Yes, that would be a great feature.

**Comment by itagagaki** [comment]
Added the button. Hope you like it.
The new version 2.2.0 has been also available on ATN.

**Comment by o0Julia0o** [comment]
Thx. Would be nice, if you could set some accounts that stays at the top or where it is. Often you use 1 or 2 accounts very often - so they should stay at the top. But the other accounts you would have to be sorted alphabetically to find them quickly.

**Comment by etherija** [comment]
Great! Thanks so much, I look forward to trying the new feature today.

On 20 Jun 2022, at 08:49, o0Julia0o ***@***.***> wrote:

﻿

Thx. Would be nice, if you could set some accounts that stays at the top or where it is. Often you use 1 or 2 accounts very often - so they should stay at the top. But the other accounts you would have to be sorted alphabetically to find them quickly.

**Comment by etherija** [comment]
New feature works a treat. The team are happy. Thanks again for adding this.
________________________________
