### ISSUE TITLE
Is the "accountssort.warning" text correct?

### ISSUE THREAD

**Issue by htgoebel** [protz/Manually-Sort-Folders#89]
accountssort.warning reads:
> Regular mail accounts, Unix Movemail accounts as well as RSS accounts must come first. Local Folders are next, and at the bottom of the list are the News accounts. You can override this by choosing either Local Folders or one of the Newsgroup accounts as default, hence putting it on top of the list.

I assume "*must* come first" is wrong, and should be something like "come fist" or "come first by default". Since if they "must" come first, why could one change the order then?

**Comment by protz** [comment]
Good catch, this text is not correct. It should indeed be "come first by default". Do you want to issue in a new string (e.g.  `accountssort.warning2`) for this?

**Comment by wsmwk** [comment]
@protz this appears to be ready to go
