### ISSUE TITLE
Startup folder does not work even if set

### ISSUE THREAD

**Issue by ghost** [protz/Manually-Sort-Folders#92]
Dear protz
https://github.com/Ximi1970/Manually-Sort-Folders/issues/5#issuecomment-534292700
Please Look at

Startup folder does not work even if set.
Launch in the last opened folder.
Please check and correct.

**Comment by protz** [comment]
Thanks, I have seen that. I don't have a whole lot of time right now, so I'll see what I can do. Any patch would be, naturally, much appreciated.

**Comment by kotaro366** [comment]
Improved startup folder settings

Once the set folder can be fixed,

Many people will be happy as in ver 60.

I hope it will be improved soon.

**Comment by John22de** [comment]
Unfortunately, the additional setting for selecting a default startup folder, such as Inbox, does not work. I have tested it with Window 10 64-bit and Thunderbird 68.1.1 64-bit.

**Comment by garvied** [comment]
Same problem with Thunderbird 68.1.2 (64 bits) on kubuntu 19.04

**Comment by gabri25ele** [comment]
not work 😥
WIn10 64bit Thunderbird 68.2 64bit

**Comment by LaurentGrenet** [comment]
Same issue, and same demand of fix, under W7 Pro 64bits / TB 68.2.0

**Comment by gabri25ele** [comment]
I noticed that if you click on the "restart thunderbird" button it works.
If you close thunderbird normally, it does not work.
very strange

**Comment by garvied** [comment]
It doesn't work for me so much if I click on restarting Thunderbird as if I close the program.
In both cases it fails.

**Comment by gabri25ele** [comment]
> 
> 
> It doesn't work for me so much if I click on restarting Thunderbird as if I close the program.
> In both cases it fails.

Strange 🤨
different behaviors, who knows what they are caused.
maybe different settings?
I tried a portable, clean thunderbird, but that's the behavior.

**Comment by gabri25ele** [comment]
trick to make it work... delete the file **session.json**
But it should be erased always we close Thunderbird. 
Then, once Thunderbird is closed to the desired folder, set the file session.json to read-only. 
That should work.

**Comment by gabri25ele** [comment]
> 
> 
> The startup folder feature works here.
> 
> Manually sort folders 2.0.2
> Thunderbird 68.3.0 with single Google IMAP account
> Windows 7 SP1 32-bit
> 
> You can use the userChromeJS extension to select the folder at startup.
> You can show the selected folder url using the error console.
> 
> More info
> http://forums.mozillazine.org/viewtopic.php?f=28&t=3057347

what code insert in userChrome.js for local folder?

**Comment by morat523035** [comment]
Here is how to show the selected folder url using the error console.

http://forums.mozillazine.org/viewtopic.php?p=14851876#p14851876

e.g. mailbox://nobody@Local%20Folders/Example for the en-US build

English build has a different username@hostname in the folder url compared to the German build.

**Comment by BillH99999** [comment]
It is also working fine here on Windows 10 1909 64-bit.

I'm running:

Manually sort folders 2.0.4
Thunderbird 68.12.0 32-bit

And also: 

Manually sort folders 2.0.4
Thunderbird 78.3.2 64-bit

Bill

**Comment by gabri25ele** [comment]
with the last update 2.0.4 works like a charm

**Comment by Webdongle** [comment]
Yes works now 2.0.5
Can someone close this thread please
