### ISSUE TITLE
Upgrade to 64bit

### ISSUE THREAD

**Issue by kanlukasz** [protz/Manually-Sort-Folders#93]
Hello,

The addon does not work on the 64-bit version of Thunderbird 68.1.1, which has been officially released for several days

I use WIN10

**Screen:** _(sorry its in Polish lang)_
![obraz](https://user-images.githubusercontent.com/30685349/65851884-b4b48c00-e354-11e9-88bd-b282b38875e3.png)

**Comment by msprotz** [comment]
Thanks. Please see #86
