### ISSUE TITLE
Settings not accessible in TB68

### ISSUE THREAD

**Issue by tooomm** [protz/Manually-Sort-Folders#99]
Unlike all the others addons I use, for "Manually Sort Folders" the addon settings are not accessible via `Menu --> Add-ons`

In the description of the extension it says that there is a new menu under `Tools`, but I just can't find it. 🙈

**Comment by wsmwk** [comment]
> Unlike all the others addons I use, for "Manually Sort Folders" the addon settings are not accessible via `Menu --> Add-ons`
I see this too.

> In the description of the extension it says that there is a new menu under `Tools`, but I just can't find it. 

![tools MSF](https://user-images.githubusercontent.com/216903/66267837-6ac02000-e804-11e9-8858-23cd5803bb94.png)

**Comment by schneeschmelze** [comment]
In TB 68.1.1 on macOS 10.13.6 there still is the menu entry that @wsmwk has shown above (in German it reads "Konten- & Ordnerreihenfolge ändern", as before, but I can confirm that there is no entry in the hamburger menu. Maybe that's what @tooomm meant to say?

**Comment by wsmwk** [comment]
I concur, settings is not available in the hamburger

**Comment by wsmwk** [comment]
This is the same as issue 50

**Comment by tooomm** [comment]
> > In the description of the extension it says that there is a new menu under `Tools`, but I just can't find it.
> 
> ![tools MSF](https://user-images.githubusercontent.com/216903/66267837-6ac02000-e804-11e9-8858-23cd5803bb94.png)

Thanks! But wow... that menu bar is *hidden in Thunderbird by default since 7 years*:
https://support.mozilla.org/en-US/kb/display-thunderbird-menus-and-toolbar

The extension should really really support the new default menu!

Also, following your references, this got reported already 6 years ago in #22. 🙈
